### ISSUE TITLE
通过权限开关@功能

### ISSUE THREAD

**Issue by konsheng** [FlickerProjects/TrChat#104]
增加@玩家开关功能，使其可以禁用或启用。

**Comment by ItsFlicker** [comment]
```yaml
  Mention:
    Enabled: true
    Self-Mention: false
    Format: '&r &a@&2{0}&r '
    Cooldown: '30s'
    Notify: true
```
Enabled不是吗
还是要每个玩家能单独开关?
