### ISSUE TITLE
关于敏感词屏蔽

### ISSUE THREAD

**Issue by mcchampions** [FlickerProjects/TrChat#122]
很尴尬的事，这个功能如果名字带敏感词也会和谐了，比如我服务器的有一个玩家名字中带了tm
还有就是自带的敏感词词库不够完善。

**Comment by 157946a** [comment]
词库是由他人提供的，这个不完全属于trchat，至于你说的，确实有过，就算中间有一个字母也会判断替换

**Comment by ItsFlicker** [comment]
> 很尴尬的事，这个功能如果名字带敏感词也会和谐了，比如我服务器的有一个玩家名字中带了tm

可以在频道文件中添加
```yaml
Events:
  Process: |-
    filter get &message
```
然后将filter.yml中的Enable.Chat设为false
