### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by SueFox** [FlickerProjects/TrChat#154]
建议添加一个让聊天过滤器只过滤玩家发出消息的功能选项，有时候一些插件发送的信息莫名其妙会变成***awa。。。。

**Comment by 157946a** [comment]
已知问题,等待修复

**Comment by ItsFlicker** [comment]
可以在频道文件中添加
```yaml
Events:
  Process: |-
    filter get &message
```
然后将filter.yml中的Enable.Chat设为false
