### ISSUE TITLE
以后台身份使用喊话功能时重复

### ISSUE THREAD

**Issue by BasinM** [FlickerProjects/TrChat#168]
服务器核心是cat1.12
服务器并没有安装CMI
这个是图片：https://s3.bmp.ovh/imgs/2022/08/05/e54b8e16cd5bd01c.png

```yaml
Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  - condition: null
    prefix:
      world:
        text: '&6[&a%multiverse_world_alias%&6]'
      player:
        text: '&e%player_name%&8: '
    msg:
      default-color: 'f'
      hover: '&7Date: %server_time_HH:mm:ss%'
      
Console:
  - prefix:
      server:
        text: '&e[&c系统&e]&8: '
    msg:
      default-color: 'b'`
```
