### ISSUE TITLE
1.19.2玩家发送消息时出错，OP发送没有问题

### ISSUE THREAD

**Issue by Maxwellboys** [FlickerProjects/TrChat#189]
Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-PRE-32                                     java.util.NoSuchElementException: Collection contains no element matching the predicate.                                        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:278) ~[TrChat-2.0.0-PRE-32.jar:?]             at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:124) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                                             at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:65) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                                           at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]                                      at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                                      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:133) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                                            at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:131) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                                    at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:78) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                            at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                            at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                               at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                               at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                  at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                  at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-2.0.0-PRE-32.jar:?]                                                                                                              at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1774]                                                                                                               at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]                                                                                                                          at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]                                                                                                                       at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[purpur-1.19.2.jar:git-Purpur-1774]           at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[purpur-1.19.2.jar:git-Purpur-1774]         at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2494) ~[?:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2675) ~[?:?]                                                                                                                at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2319) ~[?:?]                                                                                                                at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]                          at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]                               at java.lang.Thread.run(Thread.java:833) ~[?:?]                                                                 [18:06:31 INFO]: [Iris]: Mantle Size: 17 Chunks                                                                         [18:06:31 INFO]: [Iris]:   Object Mantle Size: 113 (8)                                                                  [18:06:31 INFO]: [Iris]:   Jigsaw Mantle Size: 156 (10)                                                                 [18:06:31 INFO]: [Iris]:   Carving Mantle Size: 265 (17)                                                                [18:06:31 INFO]: [Iris]: Initializing Engine: scsj/overworld (IrisRange(min=-64.0, max=448.0) height) Seed: 7233662643547978413                                                                                                                 [18:06:34 INFO]: [ProtocolLib] The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.                                                                                                          >                                                                                                                       >                                                                                                                       >

**Comment by Maxwellboys** [comment]
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color:
          - '<g:#e6755c:#e6a65c>{condition: perm "group.admin"}'
          - '<g:#e60000:#e67c00>{condition: perm "group.mvp"}'
          - '<g:#5c61e6:#5cc4e6>{condition: perm "group.vipplus"}'
          - '<g:#00e64e:#00e6a1>{condition: perm "group.vip"}'
          - '&7'
      hover: '&7发言时间: %server_time_a h:mm:ss%'
    prefix:
      world:
        text: '&8[&e%world_name%&8]'
        hover: |-
          &r
          &8▪ &f%world_name% &2%player_x%/%player_y%/%player_z%
          &r
          &6▶ &e点击申请传送此玩家
          &r
        command: '/tpa %player_name%'
      prefix1:
          text: 
          - ' &f:admin: {condition: perm "group.admin"}'
          - ' &f:mvp: {condition: perm "group.mvp"}'
          - ' &f:vipplus: {condition: perm "group.vipplus"}'
          - ' &f:vip: {condition: perm "group.vip"}'
          - ' &f:player: '
      player:
        - condition: 'player op'
          text: '%cmi_user_nickname%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击私聊他
            &r
          suggest: '/msg %player_name% '
      part-before-msg:
        text: 
          - '&7: '
    suffix:
      example:
        text: ''

**Comment by Maxwellboys** [comment]
下面是我的配置
```yaml
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color:
          - '<g:#e6755c:#e6a65c>{condition: perm "group.admin"}'
          - '<g:#e60000:#e67c00>{condition: perm "group.mvp"}'
          - '<g:#5c61e6:#5cc4e6>{condition: perm "group.vipplus"}'
          - '<g:#00e64e:#00e6a1>{condition: perm "group.vip"}'
          - '&7'
      hover: '&7发言时间: %server_time_a h:mm:ss%'
    prefix:
      world:
        text: '&8[&e%world_name%&8]'
        hover: |-
          &r
          &8▪ &f%world_name% &2%player_x%/%player_y%/%player_z%
          &r
          &6▶ &e点击申请传送此玩家
          &r
        command: '/tpa %player_name%'
      prefix1:
          text: 
          - ' &f:admin: {condition: perm "group.admin"}'
          - ' &f:mvp: {condition: perm "group.mvp"}'
          - ' &f:vipplus: {condition: perm "group.vipplus"}'
          - ' &f:vip: {condition: perm "group.vip"}'
          - ' &f:player: '
      player:
        - condition: 'player op'
          text: '%cmi_user_nickname%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击私聊他
            &r
          suggest: '/msg %player_name% '
      part-before-msg:
        text: 
          - '&7: '
    suffix:
      example:
        text: ''
```

**Comment by ItsFlicker** [comment]
在下个版本发布前可用以下修改修复
```yaml
      player:
        - condition: 'player op'
          text: '%cmi_user_nickname%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击私聊他
            &r
          suggest: '/msg %player_name% '
        - text: ''
```
