### ISSUE TITLE
[问题]: 在BC安装TrChat后Bc的PluginMessageEvent无法触发

### ISSUE THREAD

**Issue by sumdream** [FlickerProjects/TrChat#194]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

最近在写个BC的插件,在Bc监听PluginMessageEvent的时候发现BC安装了Trchat后,这个事件里面的代码都无法执行到.在BC卸载Trchat后能正确执行.

### 配置文件

```YAML
BC里面的Bungee.yml文件内容
Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  - condition: null
    prefix:
      server:
        text: '&8[&3%server_name%&8] '
        hover: |-
          &7Server &3%server_name%
          &r
          &7Version: &6%server_version%
          &7Online: &a%server_online%&7/&2%server_max_players%
          &7TPS: &b%server_tps%
      player:
        text: '&e%player_name%&8: '
    msg:
      default-color: 'f'
      hover: '&7Date: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&eServer&8: '
    msg:
      default-color: 'l'
```

### 日志

无任何日志输出

### 服务器环境

服务器版本:Waterfall1.19-R0.1-SNAPSHOT

插件列表:
1. tr-chat
2. Color-Motd
