### ISSUE TITLE
[问题]: /ignore屏蔽指令在多端口BC模式下无用

### ISSUE THREAD

**Issue by MrLaoGe** [FlickerProjects/TrChat#195]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

通过多次测试，在多端口Global.yml的情况下 /ignore 的指令并不生效也没有任何反馈提示。希望这个问题能够被修复这个功能非常具有意义价值

### 配置文件

```YAML
Options:
  # 需要权限才能发送消息
  #Speak-Condition: 'perm "trchat.global"'
  # 是否跨服
  Proxy: true
  # 是否强制跨服
  Force-Proxy: true
  # 二次转发(子服>跨服端>子服)
  Double-Transfer: true
  # 自动加入
  Auto-Join: true
  # 端口
  Ports: 50000;50001;50002;50003;50004;50005;50007;50008;50009;50010;60001;60002;60003;60004;60005;60006;60007;60008;60009
  # 50006空岛的
  
Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  #NULL
  - condition: null
    priority: 50
    prefix:
      player:
        text: '婸餏{#C0C5D1}%player_name%: '
        hover: |-
          &8%player_name% - 玩家
          &r
          &7血量: %player_health_rounded%
          &7等级: %player_level%
          &r
          &a点击私聊
        suggest: '/tell %player_name% '
    msg:
      default-color: '{#C0C5D1}'
      hover: '&7日期: %server_time_HH:mm:ss%'
```

### 日志

无相关日志报告

### 服务器环境

服务器版本:
...1.19.2 purpur，waterfall-1.19-504
