### ISSUE TITLE
[问题]: 展示物品出现了error locale的问题

### ISSUE THREAD

**Issue by HansOffice** [FlickerProjects/TrChat#203]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

聊天栏展示物品显示error locale并不直接在聊天栏内显示物品名称
版本也是最新版本的trchat
测试了两个配置文件一模一样的服务器，前者并没有出现这样的情况，而后者却出现了这样的情况

### 配置文件

```YAML
General:
  Command-Controller:
    Enabled: false
    List:
      - 'arasple{exact: true}{condition: perm *trchat.admin}'
      - 'ver(sion)?(s)?{condition: perm *trchat.admin}'
      - 'help(s)?{condition: perm *trchat.admin}'
      - 'shout{cooldown: 3}'
  Item-Show:
    Enabled: true
    Permission: 'null'
    Cooldown: '30s'
    Format: '&8[&3{0} &bx{1}&8]'
    Origin-Name: false
    Compatible: false
    Max: 5
    Keys:
      - "%i%"
      - "%i"
      - "%item%"
      - "%item"
      - "[i]"
      - "[item]"
  Mention:
    Enabled: true
    Self-Mention: false
    Permission: 'null'
    Format: '&r &a@&2{0}&r '
    Cooldown: '30s'
    Notify: true
  Inventory-Show:
    Enabled: true
    Permission: 'null'
    Cooldown: '30s'
    Format: "&8[&3{0}'s Inventory&8]"
    Keys:
      - '[inv]'
      - '[inventory]'
      - '[背包]'
  EnderChest-Show:
    Enabled: true
    Permission: 'null'
    Cooldown: '30s'
    Format: "&8[&3{0}'s Ender Chest&8]"
    Keys:
      - '[ender]'
      - '[enderchest]'
```

### 日志

没有产生报错日志

### 服务器环境

服务器版本:purpur1.19.2
...
插件列表:
...
