### ISSUE TITLE
[问题]: 总结一些使用过程中的问题

### ISSUE THREAD

**Issue by TUCAOEVER** [FlickerProjects/TrChat#204]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.使用Mention相关语法时，功能未正常赋在对应字符上
相关问题细节如下:
```
Function-Mention-Format:
  - type: json
    text: ' [&a@&2{0}] '
    args:
      - hover: '&7点击私聊!'
        suggest: '/tell {1}'
```
![image](https://user-images.githubusercontent.com/43756134/201461503-54a228f4-2963-4a1e-9400-6467aeb5b9d5.png)
此时hover和suggest都没有被正确赋在字符串上，此BUG在上一版本未复现
2.使用Inv时，菜单相关语言未提供汉化（类似的还有其他相关的菜单方法）
![image](https://user-images.githubusercontent.com/43756134/201461642-51a42b0a-f6cf-49a6-8617-f26e7179c281.png)
3.可能不算BUG，但是希望后续进行改进
服务器内如果有一位玩家叫 "TEST" 在使用 "@Test" 时，相关字符串被识别为使用Mention，“Test”替换为对应格式，但是实际上"TEST"这个玩家并没有收到提及信息，后续希望对字符大小写进行忽略即可进行@
![image](https://user-images.githubusercontent.com/43756134/201461755-41a33a48-3c1f-4dbd-856d-746cb12967f4.png)
4.服务器安装Essential时，如果被@的对象是OP，且在Ess内设置OP的名字颜色时，使用/msg私聊，并使用Tab补全时，此玩家补全名称将包含颜色字符，如果不对颜色字符进行删除，发送则会报错不合法字符被踢出服务器，如果对颜色字符删除，私信的命令将无效，无法发出
5.关于“云屏蔽”，因为各种原因可能会导致云内容无法每一次都成功下载，希望能增加离线缓存，如果无法联网更新自动从离线库读取屏蔽词。
### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本:
This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1171 (MC: 1.16.5)
插件列表:
AureliumSkills, BattlePass, BattlepassExtension, BetonQuest, Citizens, CrazyCrates, Essentials, FastAsyncWorldEdit (WorldEdit), GlowAPI, JetsMinions, LibsDisguises, LuckPerms, MMOItems, MMOMana, Multiverse-Core, MythicLib, MythicMobs, PacketListenerApi, PlaceholderAPI, PlayerPoints*, ProtocolLib, Repuska, ServerListPlus, ServerTours, ShopGUIPlus, SkinsRestorer, Skript, skript-fishing, SuperChairs, TAB, TrChat, TrHologram, TrMenu, Vault, VoidGen,
 WorldEditSUI, WorldGuard
