### ISSUE TITLE
[问题]: paper1.12.2无法发送聊天

### ISSUE THREAD

**Issue by Chaostarts** [FlickerProjects/TrChat#211]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.装上trchat
2.设置好频道为global
3.无法说话

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: BUNGEE
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Global'
```

### 日志

[11:25:19 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-RC-4
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer
        at me.arasple.mc.trchat.util.BukkitComponentUtilKt$LEGACY_SERIALIZER$2.invoke(BukkitComponentUtil.kt:40) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitComponentUtilKt$LEGACY_SERIALIZER$2.invoke(BukkitComponentUtil.kt:36) ~[?:?]
        at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitComponentUtilKt.getLEGACY_SERIALIZER(BukkitComponentUtil.kt:36) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitComponentUtilKt.legacy(BukkitComponentUtil.kt:63) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.obj.Text.process(Text.kt:30) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:23) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:22) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:149) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:128) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:62) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_341]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Paper-1.12.2.jar:git-Paper-1574]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-1.12.2.jar:git-Paper-1574]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1394) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1309) ~[Paper-1.12.2.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[Paper-1.12.2.jar:git-Paper-1574]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_341]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_341]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_341]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_341]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]

使用的是paper1.12.2

### 服务器环境

服务器版本:
1.12.2
插件列表:
Plugins (87): AdvancedCleaner, AdvancedColorSigns, AfricanOpenBox, AntiCheatReloaded, APInventory, AttributePlus, BanItem,
ChestCommands, ChunkBlocksLimit, Citizens, CleanroomGenerator, CommandBan, CommandNPC, ConsoleSpamFix, CtOnlineReward, CustomBaoShi, CustomF
ishing, CustomShop, Decompose, EasyCommand, EasyKitsRel, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn
, FarmProtect, GiveItem, GlobalShop, GroupManager, GuoItemLoreCommand, HeadDatabase, HolographicDisplays, HotSpringPlus, InfiniteScoreboard,
 IronElevators, ItemEditor, JulyGuild, JulyLibrary, LaggRemover, LevelChat, LibsDisguises, LLib, Lores, MiaoBind, Multiverse-Core, Multivers
eCoreBug, MythicMobs, MythicMobsExtension, NewCustomCuiLianPro, NOMoreDamageEffect, NoOffhand, NoSellLoreItemToGlobalShop, Notbuild, Placeho
lderAPI, PlayerPoints, PlayerTitle, PlotMe, PlotMe-DefaultGenerator, PluginManager, ProtocolLib, QuickShop, RandomForge, Residence, SaveMySp
awn, ScriptBlockPlus, Shopkeepers, ShowItem, SkinsRestorer, SX-Attribute, TAB, TimeCommand, TimeCommands, TiWen, tpLogin, Tpr, TrashBin, TrC
hat, UnbreakableEX, UpgradeEnchant, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, WorldLevelLimit
