### ISSUE TITLE
[问题]: 1.12.2spigot 1.19.3paper 1.16.5paper 使用TrChat会报错

### ISSUE THREAD

**Issue by kxkl2077** [FlickerProjects/TrChat#213]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.启用TrChat最新版
2.启用成功
3.玩家输入聊天信息
4.报错（1.12.2 1.16.5 1.19.3三个核心报错内容相同）

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: ''
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

[08:52:06 INFO]: [TrChat] Failed to catch cloud thesaurus of https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json.
[08:52:06 INFO]: java.net.SocketTimeoutException: Read timed out
[08:52:06 INFO]: [TrChat] 无法从云端更新敏感词库......
[08:52:09 INFO]: [AuthMe] The user MC_kxkl2077 has 10 accounts:
[08:52:09 INFO]: [AuthMe] §7§aMC_kxkl2077§7, wcfafawc, tmfafatm, 111, mynameisenderman, czyx_o, dreams_fans10, lirizz, lirizzseelp, haiij1015.
[08:52:09 INFO]: [AuthMe] MC_kxkl2077 logged in 192.168.10.2
[08:52:15 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-RC-6
java.lang.IllegalArgumentException: Attempt to get double field "net.minecraft.server.v1_12_R1.EntityPlayer.e" with illegal data type conversion to int
        at sun.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(Unknown Source) ~[?:1.8.0_351]
        at sun.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(Unknown Source) ~[?:1.8.0_351]
        at sun.reflect.UnsafeDoubleFieldAccessorImpl.getInt(Unknown Source) ~[?:1.8.0_351]
        at java.lang.reflect.Field.getInt(Unknown Source) ~[?:1.8.0_351]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:38) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:25) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:55) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:285) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:238) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:21) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.obj.Style$Companion.setPlaceholders(Style.kt:87) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:99) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo$default(Style.kt:92) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:25) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:22) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:149) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:128) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:62) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_351]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1323) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1261) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_351]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_351]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_351]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_351]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]

### 服务器环境

服务器版本:
...1.16.5paper 1.12.2spigot 1.19.3paper
插件列表:
...
1.19.3paper插件
 AureliumSkills, ChineseName*, CleanMOTD, CMI, CMIEInjector*, CMILib, ComboEye*, DieMessage, floodgate, GSit, InvUnload, LuckPerms, Matrix, Minepacks, OpenInv, Orebfuscator, PlaceholderAPI, ProtocolLib, SkinsRestorer, Slimefun, Themis, TrChat, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaVersion
1.12.2spigot插件
PlaceholderAPI, Stp, ViaVersion, tpLogin, floodgate, ViaBackwards, ViaRewind, LuckPerms, TrChat, Vault, Citizens, ChestCommands, CMILib, AuthMe, CMI, CMIEInjector
1.16.5paper插件
BossShopPro, ChestCommands*, Citizens, CMI, CMIEInjector*, CMILib, floodgate, GoBack*, GSit, KnapsackToGo4, LuckPerms, Matrix, MiaoBoard, Multiverse-Core, Orebfuscator, OreTeleport*, PhantomWorlds, PlaceholderAPI, ProtocolLib, QuickShop, Residence, Stp*, TrChat, UltimateTimber, Vault, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WorldEdit, XConomy
