### ISSUE TITLE
[问题]: Could not pass event PacketSendEvent to TrChat v2.0.0-RC-6 无限报错

### ISSUE THREAD

**Issue by Guyao146** [FlickerProjects/TrChat#215]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.安装TrChat当前最新版本 2.0.0-RC.6
2.启动服务器
3.无限刷报错

### 配置文件

```YAML
Settings.yml
######################################################################
#
#         Powered by TabooLib 6.0
#
#  ___________      _________ .__            __
#  \__    __________\_   ___ \|  |__ _____ _/  |_
#  |    |  \_  __ /    \  \/|  |  \\__  \\   __\
#  |    |   |  | \\     \___|   Y  \/ __ \|  |
#  |____|   |__|   \______  |___|  (____  |__|
#  \/     \/     \/  TrChat 1.9
#                                ------ Author by Arasple, Maintainer by ItsFlicker
#
######################################################################

# General options
GENERAL:
  CHECK-UPDATE: true
  DEBUG: true
  DISABLED-WORLDS: [PUT_YOUR_WORLD_NAME_HERE, ANOTHER_WORLD]
  # Log formats
  LOG-NORMAL: '[{0}] {1}: {2}'
  LOG-PRIVATE: '[{0}] {1} -> {2}: {3}'
  # The time when logs are automatically deleted (in days) 0 = disabled
  LOG-DELETE-TIME: 0
  DEPEND-EXPANSIONS:
    - 'player'
    - 'server'
    - 'vault'
  PREVENT-TAB-COMPLETE: false
  # NONE, BUNGEE, VELOCITY
  PROXY: NONE
  DATABASE:
    enable: false
    host: localhost
    port: 3306
    user: root
    password: root
    database: root
    table: trchat

# Chat Color
# Perm Node: trchat.color.<CODE>
# HEX Color require trchat.color.*
#
# Enable options
CHAT-COLOR:
  CHAT: true
  SIGN: true
  ANVIL: true
  BOOK: true

# Chat Control
CHAT-CONTROL:
  # Anti similar text repeat (Maximum similarity 0-1)
  ANTI-REPEAT: 0.85
  # Chat cooldown
  COOLDOWN: 2.0
  # Chat text length limit
  LENGTH-LIMIT: 100

formal.yml
PRIVATE_RECEIVE:
- msg:
    hover: '&7日期: %server_time_HH:mm:ss%'
    default-color: f
  parts:
  - text: '&8[&6%player_name% &7➥ &2%toplayer_name%&8] '
GLOBAL:
- - msg:
    hover: |-
      &7
      &7发送时间: &b%server_time_h:mm:ss a%
      &7
    default-color: f
  parts:
  - hover: |-
      &r
      &8▪ &7使用称号: &f&r%deluxetags_tag%&f
      &r
      &6▶ &e点击打开称号菜单
      &r
    text: '%rgb_#1a1b33%%deluxetags_tag%'
    command: /tags
  - hover: |-
      &r
      &8▪ &7公会名：%guild_name%
      &8▪ &7担任职务：%guild_member_position%
      &8▪ &7加入时间：%guild_member_join_time%
      &8▪ &7排名：%guild_ranking%
      &8▪ &7会长：%guild_owner%
      &8▪ &7人数：%guild_member_count%/%guild_max_member_count%
      &8▪ &7创建时间：%guild_creation_time%
      &8▪ &7公会币储备：%guild_bank_gmoney%
      &8▪ &7公会当前在线人数：%guild_bank_gmoney%
      &r
      &6▶ &e点击打开公会菜单
      &r
    text: '%rgb_#1a1b33%[%guild_name%]'
    command: /guild gui main
  - hover: |-
      &r
      &8▪ &7位置: &3%multiverse_world_alias%&7, &7X:%player_x% Z:%player_z%
      &8▪ &7时间: &b%multiverse_world_time%
      &8▪ &7生存时间: &b%statistic_minutes_played%分
      &r
      &6▶ &e点击发送传送请求
      &r
    text: '%rgb_#1a1b33%[&r%multiverse_world_alias%%rgb_#1a1b33%]'
    command: /tpa %player_name%
  - hover: |-
      &r
      &8▪ &7技能值: &3%aureliumskills_power% ✦
      &8▪ &7岛屿等级: &2%Level_bskyblock_island_level%
      &8▪ &7岛屿主人: &2%bskyblock_island_owner%
      &8▪ &7岛屿点赞: &2%bskyblock_likes_addon_island_likes_count% 个
      &8▪ &7成就完成: &a%aach_achievements%&f/&7%aach_total_achievements%
      &r
      &6▶ &e点击访问Ta的空岛
      &r
    text: '%rgb_#1a1b33%[%rgb_#e6b8ba%岛屿&7Lv.&6%Level_bskyblock_island_level%%rgb_#1a1b33%]'
    command: /is warps
  - text: ' '
  - hover: |-
      &r
      &8▪ &7延迟: &3%player_ping% Ms
      &8▪ &7生命值: &c%player_health_rounded% ❤
      &8▪ &7饥饿值: &3%player_saturation%
      &8▪ &7正版认证: &c暂无
      &r
      &6▶ &e点击发送私聊
      &r
    text: '%rgb_gradient_#e6d2a1:#a1e1e6_{player_name}%'
    suggest: '/msg %player_name% '
  - text: '&7: '
  priority: 2147483647
  suffix:
  - text: ''
- msg:
    hover: |-
      &7
      &7发送时间: &b%server_time_h:mm:ss a%
      &7
    default-color: f
  parts:
  - hover: |-
      &r
      &8▪ &7使用称号: &f&r%deluxetags_tag%&f
      &r
      &6▶ &e点击打开称号菜单
      &r
    text: '%rgb_#1a1b33%%deluxetags_tag%'
    command: /tags
  - hover: |-
      &r
      &8▪ &7公会名：%guild_name%
      &8▪ &7担任职务：%guild_member_position%
      &8▪ &7加入时间：%guild_member_join_time%
      &8▪ &7排名：%guild_ranking%
      &8▪ &7会长：%guild_owner%
      &8▪ &7人数：%guild_member_count%/%guild_max_member_count%
      &8▪ &7创建时间：%guild_creation_time%
      &8▪ &7公会币储备：%guild_bank_gmoney%
      &8▪ &7公会当前在线人数：%guild_bank_gmoney%
      &r
      &6▶ &e点击打开公会菜单
      &r
    text: '%rgb_#1a1b33%[%guild_name%]'
    command: /guild gui main
  - hover: |-
      &r
      &8▪ &7位置: &3%multiverse_world_alias%&7, &7X:%player_x% Z:%player_z%
      &8▪ &7时间: &b%multiverse_world_time%
      &8▪ &7生存时间: &b%statistic_minutes_played%分
      &r
      &6▶ &e点击发送传送请求
      &r
    text: '%rgb_#1a1b33%[&r%multiverse_world_alias%%rgb_#1a1b33%]'
    command: /tpa %player_name%
  - hover: |-
      &r
      &8▪ &7技能值: &3%aureliumskills_power% ✦
      &8▪ &7岛屿等级: &2%Level_bskyblock_island_level%
      &8▪ &7岛屿主人: &2%bskyblock_island_owner%
      &8▪ &7岛屿点赞: &2%bskyblock_likes_addon_island_likes_count% 个
      &8▪ &7成就完成: &a%aach_achievements%&f/&7%aach_total_achievements%
      &r
      &6▶ &e点击访问Ta的空岛
      &r
    text: '%rgb_#1a1b33%[%rgb_#e6b8ba%岛屿&7Lv.&6%Level_bskyblock_island_level%%rgb_#1a1b33%]'
    command: /is warps
  - text: ' '
  - hover: |-
      &r
      &8▪ &7延迟: &3%player_ping% Ms
      &8▪ &7生命值: &c%player_health_rounded% ❤
      &8▪ &7饥饿值: &3%player_saturation%
      &8▪ &7正版认证: &c暂无
      &r
      &6▶ &e点击发送私聊
      &r
    text: '%rgb_gradient_#e6d2a1:#a1e1e6_{player_name}%'
    suggest: '/msg %player_name% '
  - text: '&7: '
  priority: 2147483647
  suffix:
  - text: ''
PRIVATE_SEND:
- msg:
    hover: '&7日期: %server_time_HH:mm:ss%'
    default-color: f
  parts:
  - text: '&8[&a%player_name% &7➦ %toplayer_name%&3&8] '
```

### 日志

[14:20:36] [Netty Server IO #1/ERROR]: Could not pass event PacketSendEvent to TrChat v2.0.0-RC-6
java.lang.NullPointerException: null
        at me.arasple.mc.trchat.module.internal.database.DatabaseSQLite.<init>(DatabaseSQLite.kt:22) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:24) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:22) ~[?:?]
        at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases.getDatabase(Databases.kt:22) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitUtilKt.getDataContainer(BukkitUtil.kt:79) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:31) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:16) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda-0(PlayerData.kt:90) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:89) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitUtilKt.getData(BukkitUtil.kt:63) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerPackets.filter(ListenerPackets.kt:60) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:20) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at me.arasple.mc.trmenu.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:21) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:227) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### 服务器环境

服务器版本:
CraftBukkit version 3498-Spigot-b081915-10ba1be (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
插件列表:
![QQ截图20221231142420](https://user-images.githubusercontent.com/61780021/210127475-dc5e77de-888f-427a-8b7d-67552ffac4e8.png)
