### ISSUE TITLE
[问题]: 1.19.3游戏中说话null错误

### ISSUE THREAD

**Issue by jchWill** [FlickerProjects/TrChat#216]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.安装TrChat当前最新版本 2.0.0-RC.6
2.重启服务器
3.玩家在游戏中说话

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data
  Mongodb:
    client: 'mongodb://localhost:3307'
    database: trixey
    collection: chat

Chat:
  Anti-Repeat: 1.00
  Cooldown: '0s'
  Length-Limit: 256

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

![(}YNGEGVU4V$JW (YLPM_GU](https://user-images.githubusercontent.com/79404073/210138087-ed51a3fc-b5ec-4f2b-8486-7aa23d64566f.png)

### 服务器环境

服务器版本:
Previous: git-Purpur-1880(1.19.3)
[Server] * You are 2 version(s) behind
插件列表:
...
![image](https://user-images.githubusercontent.com/79404073/210138048-9e396ca6-629a-4d49-bc3c-05b8962bdcb1.png)
TRChat有问题先禁用了（）
