### ISSUE TITLE
[问题]: Trchat和Chatcolor不适配

### ISSUE THREAD

**Issue by Chaostarts** [FlickerProjects/TrChat#217]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.装上trchat和chatcolor，调整chatcolor的自定义颜色 trchat并无效果
2.使用热重载trchat可以解决问题 但是有时候会出现崩服的情况 以下是报错
希望作者可以对chatcolor插件进行适配
https://www.spigotmc.org/resources/chatcolor.22692/

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 500

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Global'
```

### 日志

[Uploading 报错.txt…]()

### 服务器环境

服务器版本:
1.19.2 purpur
插件列表:
ActionBarAPI*, ActionHealth, Admin-GUI, ajLeaderboards, AntiWorldFly, AutoUnloadChunk*, BanItem, BookEdit*, Boom, BossShopPro, BungeeTabListPlus, ChatColor, ChatEmojis, ChestCommands,Chatcolor,CommandCooldown, CommandForward, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CraftGUI, CratesLottery, CrazyAuctionsPlus, dynmap, EastLandLog4jFixer*, eBackup, EClean, EntitySearch, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, Floatingmarket, FreedomChat, GlobalMarket, GSit, HoloDrops, HolographicDisplays, InventoryRollbackPlus, JulyGuild, JulyLibrary, KeepChunks, KeywordBlock*, LangUtils*, LibsDisguises, LiteInvitation*, LiteSignIn, LuckPerms, MiaoLog4j2Fix, MiraiMC, Mobcash, MoBoxCore*, MoBoxEntityLimit*, Multiverse-Core, MythicMobs, NBTAPI, NoPlugins, OP-PW*, OpenInv, PlaceholderAPI, Plan, PlayerParticles, PlayerPoints, playertime*, PlayerTitle, PlayTimeTracker, PlugManX (PlugMan), PowerBoard, PromoteQuizz*, ProtocolLib, PublicBin, questscrolls*, QuickShop, RaiseUp, ServerMOTD, ServersNPC, Shopkeepers, ShulkerBoxBackPacks, SkinsRestorer, SlimeChunkMapPlus, spark, Stp*, SuperBan*, TabCompleteFilter, TigerReports, TrChat, UnCommand, Vault, ViaBackwards, ViaVersion, VipJoin, VipSystem, WorldEdit, WorldEditSUI, XiaoheiAutoReply*, xiaoheiBind*, xiaoheiPlayer*, XiaoheiQSManger*, YukiNoaAPI
