### ISSUE TITLE
[问题]: 玩家发言时发生 NPE

### ISSUE THREAD

**Issue by DreamUniverse843** [FlickerProjects/TrChat#219]
补充：PurPur 服务端仓库地址 https://github.com/PurpurMC/Purpur
（是一个基于 Paper 的优化端，不是模组服）

### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.玩家连接服务器
2.正常发言

### 配置文件

```YAML
频道文件

Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Auto-Join: true
  Filter-Before-Sending: true

Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  - condition: null
    prefix:
      server:
        text: '&8[&3生存服&8] '
        hover: |-
          &7服务器名称 &3生存服
          &r
          &7版本号: &6%server_version%
          &7在线数: &a%server_online%&7/&2%server_max_players%
          &7TPS: &b%server_tps%
      player:
        text: '&e§6[§c%luckperms_prefix%§6] &f%player_name%: '
    msg:
      default-color: 'f'
      hover: '&7发信时间: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&e服务器&8: '
    msg:
      default-color: 'l'
```
settings.yml
```
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Global'
```
```


### 日志

Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-RC-6
java.lang.NullPointerException
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.get(ConfigNodeTransfer.kt:21) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.checkLimits(ListenerChat.kt:125) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:35) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [?:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [?:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_342]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]

### 服务器环境

服务器版本:
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
插件列表:
Plugins (31): BetterRTP, ChestCommands, ChestCommandsPro, Chunky, CMI, CMILib, CoreProtect, CustomJoinItems*, DeluxeMenus, DeluxeTags, DieMessage, GoldenEnchants, KillNoDrop*, LiteBans, LuckPerms, Matrix, MiaoBoard, NexEngine, Orebfuscator, PlaceholderAPI, ProtocolLib, RealisticSeasons, Residence, TAB-Bridge, TrChat, UltimateTimber, Vault, ViaVersion, WorldEdit, WorldGuard, ZMusic-Addon
