### ISSUE TITLE
[issue]: 1.19.3purpur使用2.0.0-RC-6聊天产生报错

### ISSUE THREAD

**Issue by HansOffice** [FlickerProjects/TrChat#224]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

管理员聊天不会报错，玩家聊天则会报错且信息无法发出，我的1.19.2使用TrChat-2.0.0-RC-2并且配置文件相同则不会出现这样的问题
报错如下：

### configuration file

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data
  Mongodb:
    client: 'mongodb://localhost:3307'
    database: trixey
    collection: chat

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### logs

[02:11:29] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-RC-6
java.lang.NullPointerException: null
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.get(ConfigNodeTransfer.kt:21) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerChat.checkLimits(ListenerChat.kt:125) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:35) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[[聊天]TrChat-2.0.0-RC-6.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1890]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:413) ~[purpur-1.19.3.jar:git-Purpur-1890]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:99) ~[purpur-1.19.3.jar:git-Purpur-1890]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2483) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2639) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server environment

Server version:
...
Plugin list:
...
1.19.3 2.0.0-RC-6
