### ISSUE TITLE
[问题]: 加入trchat插件后玩家无法发言 发言会报错

### ISSUE THREAD

**Issue by xiaobu12319** [FlickerProjects/TrChat#226]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

如题 我加入了trchat插件 载入过程中没有任何报错 插件加载一切顺利
但是进入后玩家无法说话
一旦发言就会弹出报错
尝试更换了shaded但是依然会出现问题
没有更改任何配置文件

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: ''
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

[23:28:39] [pool-47-thread-1/WARN]: java.lang.NoSuchFieldException: no such field: net.minecraft.entity.player.EntityPlayerMP.playerConnection/net.minecraft.network.NetHandlerPlayServer/getField
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MemberName.makeAccessException(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MethodHandles$Lookup.findGetter(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:14)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10)
[23:28:39] [pool-47-thread-1/WARN]:     at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:34)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.module.nms.PacketSender.getConnection(PacketSender.kt:46)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.module.nms.PacketSender.sendPacket(PacketSender.kt:26)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.module.nms.MinecraftServerUtilKt.sendPacketBlocking(MinecraftServerUtil.kt:101)
[23:28:39] [pool-47-thread-1/WARN]:     at me.arasple.mc.trchat.taboolib.module.nms.MinecraftServerUtilKt.sendPacket$lambda-4(MinecraftServerUtil.kt:88)
[23:28:39] [pool-47-thread-1/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.Thread.run(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]: Caused by: java.lang.NoSuchFieldError: playerConnection
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[23:28:39] [pool-47-thread-1/WARN]:     at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
[23:28:39] [pool-47-thread-1/WARN]:     ... 21 more

### 服务器环境

This server is running CatServer version git-CatServerAsync-1.12.2-99dcf0c (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)
[23:32:58] [Server thread/INFO]: Plugins (128): RPGItems, AntiExplosion, ServerMonitor, PokeSpawnBan, Stp, PlugMan, CrispyAntiWDL, EndBattle, Akitashine, antiRedstoneClock, AllMusic, NoSellLoreItemToGlobalShop, PokemonPlugin, AntiBookAndPenBug, LegendaryProtect, AntiCraft, PokeTC, PokemonUnlimitedAttribute, LiteItemShow, TrainerFX, UBBDispenserShulkerBoxFixer, QiMengItemManage, Skript, TabletAPI, nofly, warps, PDevTool, PixelmonSpawnTitle, PokeLegendBroadcast, ProtocolLib, Notbuild, FixillegalName, CommandBan, PokeBackup, Lores, MiracleEvolve, PluginConstructorAPI, PlaceholderAPI, GroupManager, PixelmonPvp, PixelmonBattleEndHealth, HealLinCatServer, GuoItemLoreCommand, MCheatEngine, TrChat, Pokemon-Skill-Tips, BanItem, SuperOptimization, VexView, PokemonEventLog, CoreProtect, WorldEdit, AntiItemInteract, PixelmonFreeBreed, Awc, PokeStar, WorldBorder, NoEggs, TimeCommands, CmdCoolDown, LimitLegendarySpawn, SignEdit, OP-Arbiter, OnlineReward, StarLauncher_verification_Bukkit, PixelmonDialog, DragonCore, GlobalShop, PlugManX, Vault, ServerToolBox, PokeGuild, VexSign2, PokeTradeEvolution, HolographicDisplays, PlayerPoints, DeluxeTags, ChestCommands, AkitaMintItemControl, AdvancedKitsReloaded, WhoI, NyEconomy, spark, MessageAnnouncer, MiaoBoard, TAB, HundredWarsAPI, CrazyCrates, HolographicExtension, PaidCommand, AkitaBottleCap, VexKeyBoardHelper, PlotSquared, LiteLottery, BetterRTP, WowSuchCleaner, Essentials, ColorMOTD, PokeJobs, EnderContainers, NyaaCore, SakuraMove, ScriptBlockPlus, MoreTP, Marriage, Multiverse-Core, GreatFireWall, EssentialsChat, PokemonHuntArean, QuickShop, AutoSpawnWorld, Multiverse-Patches, EssentialsProtect, EssentialsSpawn, Residence, LockettePro, PokemonAPI, PokeTaskPlugin, PixelExtras, PokemonInfo, Fixer, PokemonSkin, TradeBlackList, PokePlate, AyCore, RenameCard, TXZ, WishingWells
>
