### ISSUE TITLE
[问题]: Trchat一说话就报错

### ISSUE THREAD

**Issue by Chaostarts** [FlickerProjects/TrChat#230]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

启动服务器
说话就会报错
删除EssentialsChat之后会正常 但是没有了前缀和后缀
在其他服务器用的相同配置 相同EssChat则无这个问题

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 1
  Cooldown: '2.0s'
  Length-Limit: 500

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Global'
```

### 日志

[13:39:54] [Server thread/INFO]: [�յ���] [���뽭��]CentreKiller ? 6
[13:39:57] [Async Chat Thread - #11/ERROR]: Could not pass event AsyncPlayerChatPreviewEvent to EssentialsChat v2.19.7
java.util.UnknownFormatConversionException: Conversion = 'L'
	at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.earth2me.essentials.chat.processing.AbstractChatHandler.handleChatFormat(AbstractChatHandler.java:115) ~[EssentialsXChat-2.19.7.jar:?]
	at com.earth2me.essentials.chat.processing.SignedChatHandler$PreviewLowest.onPlayerChatPreview(SignedChatHandler.java:84) ~[EssentialsXChat-2.19.7.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-"476ef25"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatDecorationProcessor.post(ChatDecorationProcessor.java:115) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
	at io.papermc.paper.adventure.ChatDecorationProcessor.processLegacy(ChatDecorationProcessor.java:68) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
	at io.papermc.paper.adventure.ChatDecorationProcessor.lambda$process$0(ChatDecorationProcessor.java:57) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 服务器环境

服务器版本:
Paper1.19.2
插件列表:
...
![Screenshot_20230131_172847_edit_1059404895730554](https://user-images.githubusercontent.com/89688029/215722170-dbf17799-8ef5-4703-bde4-5d423b3d168c.jpg)
