### ISSUE TITLE
[问题]: 当玩家拥有LP前后缀时私聊不可用

### ISSUE THREAD

**Issue by Mu-cream** [FlickerProjects/TrChat#232]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在使用tell等私聊指令时，必须使用自动填充内容(包含玩家完整前后缀，即DisplayName而非UserName)作为私聊对象，否则将会返回红色错误提示 "错误的命令参数"，
当玩家DisplayName含有空格时，返回红色错误提示 “错误的命令参数”
当玩家DisplayName含有前后缀但不含空格时，提示私聊玩家不在线

@玩家需包含完整 DisplayName，既需要附上前后缀才可生效

### 配置文件

```YAML
Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Sender:
  - prefix:
      sender:
        text: '&8[&a%player_name% &7➦ %trchat_toplayer%&3&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&8[&6%player_name% &7➥ &2%trchat_toplayer%&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'
```

### 日志

无

### 服务器环境

服务器版本:1.18.2
插件列表:
Chunky (1.3.38)                
VoidWorld (1.1)                
PlaceholderAPI (2.11.2)        
Boom (2.0.7)                   
HolographicDisplays (3.0.0)    
ConsoleSpamFix (1.9.0)         
Insights (6.11.0)              
UltimateAntiBot (4.0.5-ABYSS)  
Yum (2.9.5-git-18dc9)          
SmartInvs (1.2.7)              
ViaVersion (4.5.1)             
ViaBackwards (4.5.1)           
LuckPerms (5.4.52)             
OpenInv (4.2.1)                
CrazyAuctionsPlus (1.3.2.1)    
spark (1.9.45)                 
ChunkyBorder (1.1.34)          
LoneLibs (1.0.21)              
ProtocolLib (4.8.0)            
ILoreEdit (2.5.1)              
LiteInvitation (1.4.8-SNAPSHOT) 
LiteSignIn (1.6.5.2)           
DAutoMessage (1.4)             
NotTooExpensive (1.3.4)        
SQLibrary (7.1)                
MapPicture (1.0.0)             
Vault (1.7.3-b131)             
floodgate (2.2.0-SNAPSHOT )    
ViaRewind (2.0.2)              
RPGHorses (1.2.18)             
LiteLottery (1.3.1)            
SkinsRestorer (14.2.4)         
Themis (0.14.5)                
ChestCommands (4.0.3)          
PistonMOTD (5.0.1)             
Orebfuscator (5.3.2)           
Geyser-Spigot (2.1.0-SNAPSHOT) 
NexEngine (2.2.8 build-19/)    
Companions (1.9.4)             
Essentials (2.20.0-dev+15-2)   
AnnouncerPlus (1.3.3)          
LocketteX (1.7.8)              
XConomy (2.19.5)               
FastAsyncWorldEdit (2.4.10-SNAPSHOT) 
TAB (3.1.4)                    
ScriptBlockPlus (2.2.2)        
Matrix (6.9.5)                 
PlotSquared (6.9.1-SNAPSHOT)   
PlayerPoints (3.2.4)           
WorldGuard (7.0.7+216b061)     
antiRedstoneClock (1.5.0)      
GSit (1.2.8)                   
EssentialsSpawn (2.20.0-dev+20-5) 
CoreProtect (21.2)             
Guilds (3.5.6.3)               
Multiverse-Core (4.3.1-b861)   
KeepInventory (1.3-SNAPSHOT)   
Citizens (2.0.30-SNAPSHOT)     
Shopkeepers (2.16.3)           
ExcellentCrates (4.1.5)        
GlobalMarket (3.2.16)          
AureliumSkills (Beta 1.3.10)   
AuthMe (5.6.0-SNAPSHOT-)       
MythicMobs (5.2.1-SNAPSHOT-)   
AreaShop (2.6.0)               
CMILib (1.2.3.6)               
Residence (5.0.2.0)            
WaterLimiter (2.2.0)           
MythicLib (1.5)                
MyPet (3.12)                   
MMOItems (6.9)                 
BanItem (3.4)                  
NBTAPI (2.11.1)                
Creamsitemx (1.0)              
WkKit (1.0.7)                  
Creamsbind (1.0)               
CreamsAlmighty (2.0.0)         
TrMenu (3.1.18)                
BetterRTP (3.4.4)              
Creamsrank (1.0)               
ServerBooster (1.1.3)          
TrChat (2.0.0-RC-6)
