### ISSUE TITLE
[问题]: 说话报错

### ISSUE THREAD

**Issue by Poeight** [FlickerProjects/TrChat#233]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

说话报错,核心为Purpur-1.18.1-build1566.jar,更换1.18.2purpur及1.18.1spigot均无此情况,

### configuration file

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: ''
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### logs

[22:26:14] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-RC-7
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
	at me.arasple.mc.trchat.util.BukkitComponentUtilKt.<clinit>(BukkitComponentUtil.kt:52) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.format.obj.Text.process(Text.kt:30) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:23) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:22) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:22) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:149) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:128) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:62) ~[TrChat-2.0.0-RC-7.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-RC-7.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-2.0.0-RC-7.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1566]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2166) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

### Server environment

Server version:
Purpur-1.18.1-build1566.jar
Plugin list:
Plugins (30): Adyeshach, Chemdah, CMILib, CustomShop, GPS, GuoScript, HolographicDisplays, ItemsAdder, LibsDisguises, LoneLibs, Lores*, LuckPerms, MMOCore, MMOItems, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, PlaceholderAPI, PlayerPoints, ProtocolLib, ScriptBlockPlus, TrChat, TrMenu, Vault, VoidGen, Vulpecula, WkKit, WorldEdit, Zaphkiel
