### ISSUE TITLE
[问题]: MultiPaper端在Global频道说话无反应

### ISSUE THREAD

**Issue by Shizuri23** [FlickerProjects/TrChat#234]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

https://user-images.githubusercontent.com/46082179/216597090-e839545a-cb81-4fff-88d0-bd9a91bb0663.mp4
将设置中的Proxy设置为False恢复正常
尝试使用Redis，结果同样问题
使用其他服务端Global则正常使用

### 配置文件

```YAML
Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  - condition: null
    prefix:
      server:
        text: '&8[&3%server_name%&8] '
        hover: |-
          &7Server &3%server_name%
          &r
          &7Version: &6%server_version%
          &7Online: &a%server_online%&7/&2%server_max_players%
          &7TPS: &b%server_tps%
      player:
        text: '&e%player_name%&8: '
    msg:
      default-color: 'f'
      hover: '&7Date: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&eServer&8: '
    msg:
      default-color: 'l'
```

### 服务器环境

服务器版本:
This server is running MultiPaper version git-MultiPaper-"8096d37" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8096d37 on HEAD)
Error obtaining version information
Previous version: MultiPaper-1.19.2-37 (MC: 1.19.2)
插件列表:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/46082179/216597446-084c50b3-5be5-48e4-bcf4-619a5f6a5564.png">
