### ISSUE TITLE
[问题]: 关闭服务器时候,报错

### ISSUE THREAD

**Issue by yangguangjin** [FlickerProjects/TrChat#237]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在关闭服务器的时候出现的错误

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: true
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: BUNGEE

Database:
  Method: SQL
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: 123456
    database: minecraft_forverworld
    table: trchat_user_data

Redis:
  enabled: true
  channel: 'lobby'
  subscribe: 
  - lobby
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: '普通'
```

### 日志

禁用 TrChat v2.0.0-PRE-37 时发生错误 (它是最新的吗？)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:105) ~[CraftScheduler.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:166) ~[CraftScheduler.class:?]
	at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:133) ~[BukkitRunnable.class:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:53) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.submitAsync(Executor.kt:53) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.submitAsync$default(Executor.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.invoke(BukkitProxyProcessor.kt:36) ~[?:?]
	at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$BungeeSide.invoke(BukkitProxyProcessor.kt:135) ~[?:?]
	at me.arasple.mc.trchat.api.impl.BukkitProxyManager$processor$2.invoke(BukkitProxyManager.kt:66) ~[?:?]
	at me.arasple.mc.trchat.api.impl.BukkitProxyManager$processor$2.invoke(BukkitProxyManager.kt:62) ~[?:?]
	at kotlin1810.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at me.arasple.mc.trchat.api.impl.BukkitProxyManager.getProcessor(BukkitProxyManager.kt:62) ~[?:?]
	at me.arasple.mc.trchat.api.impl.BukkitProxyManager.close(BukkitProxyManager.kt:94) ~[?:?]
	at me.arasple.mc.trchat.module.internal.TrChatBukkit.onDisable(TrChatBukkit.kt:68) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onDisable(BukkitPlugin.java:150) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:179) ~[JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:341) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:417) [SimplePluginManager.class:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:411) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:443) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:506) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361]

### 服务器环境

服务器版本:
...1.12.2
插件列表:
ProtocolLib
LuckPerms-Bukkit-5.4.66
