### ISSUE TITLE
大多数需要设置的插件,都会把内容打出去

### ISSUE THREAD

**Issue by xiaofengv233** [FlickerProjects/TrChat#240]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.配置抽奖箱的概率,然后就把字打出去了
2.设置cmi的悬浮字也是 
3.删除trchat就不会这样,不会出现字,cmi的chat那两个配置我关了的
![K LOE9A{HHC O7LU1$6Z@3N](https://user-images.githubusercontent.com/24617660/228501898-86a2f04c-9249-406e-ad70-23ba80a0e04b.png)

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 1.00
  Cooldown: '0.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本: 1.19.3 purpur核心
...
插件列表:
...
[](url)
![X2WP1KIN%E0PD_@Y}9WUG8K](https://user-images.githubusercontent.com/24617660/228501665-ebc5479b-d346-4db1-b4b8-503c5828ff2a.png)
