### ISSUE TITLE
[问题]: 敏感词无法取消

### ISSUE THREAD

**Issue by CloudPast** [FlickerProjects/TrChat#243]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

关了所有敏感词相关的配置
但是服务器内还是会被替换

### 配置文件

```YAML
Enable:
  Chat: false
  Sign: false
  Anvil: false
  Item: false

Cloud-Thesaurus:
  Enabled: false
  Ignored: ['nt']
  Urls: ''

Local: ''

Ignored-Punctuations: ['!','.',',','#','$','%','&','*','(',')','|','?','/','@','"','\',';','[',']','{','}','+','~','-','_','=','^','<','>',' ','　','！','。','，','￥','（','）','？','、','“','‘','；','【','】','——','……','《','》','\\', '`']
WhiteList: ['has been']
Replacement: '*'
```

### 服务器环境

This server is running CatServer version 1.16.5-7e2679e9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

Plugins (38): MiniMOTD, LuckPerms, PlaceholderAPI, ZaxLib, PokemonVariable, AkitaPokeCheck, AkitaCatch, ProtocolLib, AkitaRace, AyCore, SkinsRestorer, TrChat, Pokemon-Skill-Tips, SpawnLegTime, AkitaFlute, AntiBuild, NBTAPI, Shift_Menu, Vault, ZPokeSpring, ZPokeClean, WorldEdit, YukiNoaAPI, AdvancedOptimizer, GriefDefender, PixelmonPvp, XConomy, PlayerPoints, PokeTaskPlugin, TrMenu, OnlineReward, BanIt, PlotSquared, Multiverse-Core, AuthMe, CMILib, CMI
