### ISSUE TITLE
[问题]: Trchat跨服聊天端口限制功能无法正常使用

### ISSUE THREAD

**Issue by chencu5958** [FlickerProjects/TrChat#245]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.使用Velocity3.2.0（使用Modern转发）
2.搭建三个papermc服务端实例（也已开启Modern转发支持）
3.其中两个设置为相互互通
4.正常情况下应为AB两个服务器可以收到消息，C服务器无法收到消息，但ABC服务器都可以收到消息

### 配置文件

```YAML
默认配置，仅使用了Redis数据库配置用于跨代理端聊天（Redis版本为7.0.8，操作系统Windows Server 2019）
```

### 日志

无报错日志，Ports功能无法正常使用

### 服务器环境

服务器版本:
Papermc-1.18.2-388
Purpur-1.19.2
插件列表:
...

**Comment by chencu5958** [comment]
排除了下可能是Redis通信的问题，这个是我那边使用的Redis配置，但暂时还不确定具体原因
```YAML
Redis:
  enabled: true
  channel: 'Global'
  subscribe: ['Global']
  host: localhost
  port: 6379
  auth: 'password'
  connect: 32
  timeout: 1000
````
