### ISSUE TITLE
[问题]: 无法加载数据库驱动

### ISSUE THREAD

**Issue by While941** [FlickerProjects/TrChat#246]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

启动就时候无法加载数据库驱动
看上去像是核心的问题，spigot 1.19.2-1.19.4都试过了同样的问题，paper1.19.4确是正常的

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO

Database:
  Method: SQL
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

[05:14:56] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: trchat [2.0.0-PRE-38]
[05:14:56] [Server thread/WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[05:14:56] [Server thread/INFO]: HikariPool-2 - Starting...
[05:14:56] [Server thread/WARN]: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[05:14:57] [Server thread/ERROR]: HikariPool-2 - Exception during pool initialization.
[05:14:57] [Server thread/ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-38 (Is it up to date?)
[05:14:57] [Server thread/INFO]: [MysqlPlayerDataBridge] Enabling MysqlPlayerDataBridge v4.8.4
[05:14:57] [Server thread/INFO]: [MysqlPlayerDataBridge] Loading the config file...
[05:14:57] [Server thread/INFO]: [MysqlPlayerDataBridge] Vault dependency found.

### 服务器环境

服务器版本:
spigot 1.19.2
插件列表:
