### ISSUE TITLE
[问题]: Task Error

### ISSUE THREAD

**Issue by FBDKPlus** [FlickerProjects/TrChat#247]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

报错，但正常使用，不过对于其他一些插件聊天输入方式读取玩家自定义内容，会重复出现在聊天上

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO

Database:
  Method: SQL
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: meta_trchat
    password: 123123
    database: meta_trchat
    table: trchat_user_data

Redis:
  enabled: true
  channel: 'Bungee'
  subscribe: [Bungee]
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Bungee'
```

### 日志

[22:17:40 WARN]: [TrChat] Plugin TrChat v2.0.0-PRE-38 generated an exception while executing task 108
java.lang.NullPointerException: Cannot invoke "me.arasple.mc.trchat.module.internal.filter.processer.WordNode.isLast()" because "fnode" is null
        at me.arasple.mc.trchat.module.internal.filter.processer.Filter.addSensitiveWord(Filter.java:60) ~[TrChat-2.0.0-PRE-38.jar:?]
        at me.arasple.mc.trchat.api.impl.DefaultFilterManager.loadCloudThesaurus(DefaultFilterManager.kt:89) ~[TrChat-2.0.0-PRE-38.jar:?]
        at me.arasple.mc.trchat.api.impl.DefaultFilterManager$loadFilter$1.invoke(DefaultFilterManager.kt:67) ~[TrChat-2.0.0-PRE-38.jar:?]
        at me.arasple.mc.trchat.api.impl.DefaultFilterManager$loadFilter$1.invoke(DefaultFilterManager.kt:66) ~[TrChat-2.0.0-PRE-38.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrChat-2.0.0-PRE-38.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-448]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 服务器环境

服务器版本: PaperSpigot 1.19.3-448
...
插件列表:[22:21:03 INFO]: Server Plugins (55):
[22:21:03 INFO]: Paper Plugins:
[22:21:03 INFO]:  - HuskHomes
[22:21:03 INFO]: Bukkit Plugins:
[22:21:03 INFO]:  - AdvancedAchievements, AdvancedEnchantments, Citizens, CMI, CMILib, ConsoleSpamFix, CtOnlineReward, CustomCrops, CustomFishing, DeathMessages
[22:21:03 INFO]:  ExcellentCrates, GeekPermdrop, GlobalMarketPlus, HeadDatabase, HuskSync, Invero, ItemsAdder, LiteSignIn, LoneLibs, LuckPerms
[22:21:03 INFO]:  MagicCosmetics, mcMMO, McmmoGui, MetaInvite, MinePay, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, NexEngine
[22:21:03 INFO]:  PlaceholderAPI, PlayerGuild, PlayerPoints, PlayerTask, PlayerTitle, PlayerWarp, PlugManX, ProtocolLib, QuickShop, ShopPro
[22:21:03 INFO]:  Slimefun, SlimeGlue, TAB-Bridge, TradeMe, TrChat, TrMenu, Vault, ViaBackwards, ViaVersion, WkKit
[22:21:03 INFO]:  WorldBorder, WorldEdit, WorldGuard, XConomy
...
