### ISSUE TITLE
[问题]: paper1.19.4会报错

### ISSUE THREAD

**Issue by While941** [FlickerProjects/TrChat#250]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

paper服务器起服后会报错，报错信息如下
[20:14:50] [Craft Scheduler Thread - 16 - TrChat/WARN]: [TrChat] Plugin TrChat v2.0.0-PRE-38 generated an exception while executing task 3774
java.lang.NullPointerException: Cannot invoke "me.arasple.mc.trchat.module.internal.filter.processer.WordNode.isLast()" because "fnode" is null
	at me.arasple.mc.trchat.module.internal.filter.processer.Filter.addSensitiveWord(Filter.java:60) ~[[聊天]TrChat-2.0.0-PRE-38.jar:?]
	at me.arasple.mc.trchat.api.impl.DefaultFilterManager.loadCloudThesaurus(DefaultFilterManager.kt:89) ~[[聊天]TrChat-2.0.0-PRE-38.jar:?]
	at me.arasple.mc.trchat.api.impl.DefaultFilterManager$loadFilter$2.invoke(DefaultFilterManager.kt:72) ~[[聊天]TrChat-2.0.0-PRE-38.jar:?]
	at me.arasple.mc.trchat.api.impl.DefaultFilterManager$loadFilter$2.invoke(DefaultFilterManager.kt:71) ~[[聊天]TrChat-2.0.0-PRE-38.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[[聊天]TrChat-2.0.0-PRE-38.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-540]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

![111](https://github.com/TrPlugins/TrChat/assets/55281123/498ab203-9fc8-4c64-be7d-7b4305c9f69f)

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO

Database:
  Method: SQL
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: 124164216
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本:
paper1.19.4
插件列表:
...
