### ISSUE TITLE
[问题]: 私聊提醒不生效

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#255]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 向某人发送私聊
2. 发现接受者的actionbar没有提醒，也没有声音提醒

就是默认配置文件里的actionbar私聊提醒，我只改了颜色和声音类型，通过 私聊自己的方式 以及 别人私聊自己的方式 已经测试了，没有效果。
艾特的提醒是有效的，就是私聊没有提醒。

PS: 服务端是Waterfall + Paper的形式，都已安装TrChat-2.0.0-PRE-40

### 配置文件

```YAML
Private.yml

Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Filter-Before-Sending: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Sender:
  - prefix:
      sender:
        text: '&#bfd7fd%player_displayname% &7➦ &#ff95a7%trchat_toplayer%'
        hover: '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'
      part-before-msg:
        text: ' &8» '
        hover: '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'
    msg:
      default-color: ''
      hover: '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&#ff95a7%player_displayname% &7➥ &#bfd7fd%trchat_toplayer%'
        hover: 
        - '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'
        - '&f▶ 点击回复'
        suggest: '/msg %player_name% '
      part-before-msg:
        text: ' &8» '
        hover: 
        - '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'
        - '&f▶ 点击回复'
        suggest: '/msg %player_name% '
    msg:
      default-color: ''
      hover: 
      - '&#bfd7fd发送时间: &#ff95a7%server_time_yyyy-MM-dd HH:mm:ss%'
      - '&f▶ 点击回复'
      suggest: '/msg %player_name% '






zh_CN.yml 的部分

Private-Message-Receive:
  - type: actionbar
    text: '§x§f§f§9§5§a§7[ ! ] §x§b§f§d§7§f§d你收到来自 §x§f§f§9§5§a§7{0} §x§b§f§d§7§f§d的一条私聊消息'
  - type: sound
    sound: 'BLOCK_NOTE_BLOCK_CHIME'
    volume: 1
    pitch: 1
```

### 日志

无错误

### 服务器环境

服务器版本:
This server is running Paper version **git-Paper-47 (MC: 1.20.1)** (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aea9cdd)

插件列表:
Server Plugins (50):

**Paper Plugins:**
BKCommonLib

**Bukkit Plugins:**
AcceptTheRules, ajAntiXray, AllMusic, artEssentials, BanItem, BetterSlimeChunks, BlockLocker, ChestCommands, Citizens, CMILib
CoreProtect, CoreProtectTNT, DecentHolograms, Essentials, EssentialsProtect, EssentialsSpawn, *FarmProtect, Graves, GSit, Images
IronElevators, LuckPerms, Marriage, Multiverse-Core, NoMushroomInEnd, OpenInv, pHD, PlaceholderAPI, PluginManager, ProtocolLib
PvPToggle, QuickShop, Residence, SmoothSleep, spark, SuperVanish, *SyncTimeAndWeather, TAB, TickMonitor, TitleManager
TrChat, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags, xaero-map-spigot
