### ISSUE TITLE
[问题]: 与最新版CMI一起使用会导致消息以原版和TrChat的方式一共输出两次

### ISSUE THREAD

**Issue by humonia-sys** [FlickerProjects/TrChat#256]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.装一个CMI-9.6.0.6和TrChat-2.0.0-PRE-40
2.发现有两次消息
3.把CMI卸载掉
4.发现只有一遍TrChat的了
![](https://github.com/TrPlugins/TrChat/assets/85441099/0582f398-50a4-4dee-afc0-9243c4f9017f)

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO

Database:
  Method: SQL
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: user
    password: 'MyPassWord'
    database: trchat
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 1.00
  Cooldown: '0.3s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本:
![](https://github.com/TrPlugins/TrChat/assets/85441099/b4d0a261-0f8e-41f2-abb2-5ad6d03c0d7f)

插件列表:
![](https://github.com/TrPlugins/TrChat/assets/85441099/67fccbf0-3d03-408a-84ed-68a9599d7372)
