### ISSUE TITLE
[问题]: 1.20.1玩家发不出消息，会报错然后服务器会自动关机

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#257]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

吧插件和前置插件放入服务器
启动服务器加载完毕
进入玩家
玩家发消息
玩家会发不出消息（玩家看不到服务端也看不到）
开始报错
一会服务器自动关闭

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: ''
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

log过长打包文本档
[新建文本文档 (3).txt](https://github.com/TrPlugins/TrChat/files/11883177/3.txt)

### 服务器环境

服务器版本:
...服务器版本1.20.1
插件列表:
列表在文件里
[plugins.txt](https://github.com/TrPlugins/TrChat/files/11883149/plugins.txt)
