### ISSUE TITLE
[问题]: 与BlockLocker问题

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#258]
### 是否已尝试最新的版本

- [x] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

无法在锁箱 锁门上 打 [ ]  会消失

### 配置文件

```YAML
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&r'
      hover: '&7时间: %server_time_a h:mm:ss %'
    prefix:
      prefix:
        text: '[&b%server_time_a:hh:mm%&r] &3%luckperms_prefix%&r | '
        hover: |-
          &r
          &8▪ &7位置: &3%player_world%
          &r
          &6▶ &e点击这里发送传送请求
          &r
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&4%player_name%'
          hover: |-
            &r
            &8▪ &7延迟: &3%player_ping% 毫秒
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击联系管理员
            &r
          suggest: '/tell %player_name% '
        - text: '&r%player_name%'
          hover: |-
            &r
            &8▪ &7延迟: &3%player_ping% 毫秒
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击与我聊天
            &r
          suggest: '/tell %player_name% '
      part-before-msg:
        text: ' &r>> '
    suffix:
      example:
        text: ''
```

### 日志

无错误

### 服务器环境

服务器版本:
purpur-1.20.1-2005
插件列表:
Bukkit Plugins: (40):
 Banker, BlockLocker, Citizens, CMI, CMILib, DiscordSRV, Elevator, HeadDatabase, InteractionVisualizer, InteractiveChat
InteractiveChatDiscordSrvAddon, Invero, ItemsAdder, LibsDisguises, LoneLibs, LotteryItem, LuckPerms, MangoQuestReloaded, MMOItems, Multiverse-Core
MythicLib, MythicMobs, NBTAPI, NeigeItems, NoPlugins, PlaceholderAPI, PlayerChat, PlayerGuild, PlayerPoints, PlayerTitle
ProtocolLib, QuickShop, Residence, RPGInventory, Shopkeepers, spark, TAB, TrMenu, Vault, WorldEdit
