### ISSUE TITLE
[问题] player拓展问题和聊天消息验证失败问题

### ISSUE THREAD

**Issue by 982074664** [FlickerProjects/TrChat#263]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

一直刷屏这个报错
只要加载就刷屏

另外玩家被@后可能会被t出服务器
理由是:聊天消息验证失败
这个是不管离线玩家还是正版都会遇到
服务器版本1.20.1

### 配置文件

```YAML
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&f'
      hover: '&时间: %server_time_h:mm:ss a%'
    prefix:
      world:
        text: '[%playerTitle_use%]&b[%kingdoms_name%]&a[%player_level%级]:'
        hover: |-
          &r
          &8▪ &坐标: &3%player_world%&7, &2%player_x%/%player_y%/%player_z%
          &r
          &6▶ &e点击发送一个传送请求
          &r
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&4%player_name%'
          hover: |-
            &r
            &8▪ &7延迟: &3%player_ping% Ms
            &8▪ &7血量: &c%player_health_rounded% ❤
            &r
            &6▶ &e点击联系管理员
            &r
          suggest: '/tell %player_name% '
        - text: '&7%player_name%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &r
            &6▶ &eClick to chat with me
            &r
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&e: '
    suffix:
      example:
        text: ''
```

### 日志

[19:12:31 WARN]: java.lang.NoSuchFieldException: ping
[19:12:31 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[19:12:31 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.getPing(PlayerExpansion.java:224)
[19:12:31 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:184)
[19:12:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[19:12:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[19:12:31 WARN]:        at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:21)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.util.BukkitUtilKt.setPlaceholders(BukkitUtil.kt:55)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:92)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo$default(Style.kt:85)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:23)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:134)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onChat(ListenerBukkitChat.kt:48)
[19:12:31 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[19:12:31 WARN]:        at TrChat-2.0.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[19:12:31 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:12:31 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:12:31 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:12:31 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:12:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[19:12:31 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414)
[19:12:31 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100)
[19:12:31 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2404)
[19:12:31 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2560)
[19:12:31 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2233)
[19:12:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[19:12:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[19:12:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:12:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:12:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### 服务器环境

服务器版本:
Previous version: git-Paper-56 (MC: 1.20.1)
插件列表:
[19:14:53 INFO]: Bukkit Plugins:
[19:14:53 INFO]:  - AntiCobbleMonster, AuthMe, BanIt, 
[19:14:53 INFO]:  Essentials, EssentialsSpawn
[19:14:53 INFO]:  GuizhanLibPlugin, HardcoreSlimefun, HoloMobHealth, HotbarPets, HsRails, InteractionVisualizer, Interface4, Kingdoms, Kingdoms-Addon-Map-Viewers, Kingdoms-Addon-Outposts
[19:14:53 INFO]:  LightAPI,Multiverse-Core, NBTAPI, NekoMaid
[19:14:53 INFO]:  Notbuild, OpenInv, PlaceholderAPI, PlayerTitle, PlugManX, PotionExpansion, ProtocolLib
[19:14:53 INFO]:   *SetHome, SkinsRestorer, SlimeCustomizer, Slimefun, SlimefunItemExpansion, SlimefunNukes, SlimefunOreChunks, SlimefunWarfare, SlimeGlue
[19:14:53 INFO]:  SlimeSec, SlimeTinker,, SlimyTreeTaps, Snow-BetterRTP, *TelePortRandom, *TPAPro, TrChat, 
[19:14:53 INFO]:  Uniporter, Vault, ViaBackwards, ViaRewind, ViaVersion, VillagerUtil, WorldEdit, XConomy, YukiNoaAPI
