### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by xiaojinxs69** [FlickerProjects/TrChat#264]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

群组服玩家发消息发不出去。trchat reload就可以发送了。后台是有消息的但是客户端不显示。也没有报错应该是和bc握手的问题

### configuration file

```YAML
Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

#Bindings:
#  Prefix: ['!all']
#  Command: ['global', 'all', 'shout']

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&f'
      hover: '&7日期: %server_time_h:mm:ss a%'
    prefix:
      world:
        text: '&4[&c%playerGuild_name%&6]&8[&3%multiverse_world_alias%&8]&f[&3%luckperms_prefix%&f]'
        hover: |-
          &r
          &6▶ &e点击发送传送请求
          &r
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&f『&6&l游戏管理&f』&f%player_name%'
          hover: |-
            &r
            &8▪ &7延迟: &3%player_ping% Ms
            &8▪ &7血量: &c%player_health_rounded% ❤
            &8▪ &6玩家点卷: &a%playerpoints_points%
            &8▪ &6玩家金币: &a%cmi_user_balance%
            &8▪ &6玩家血量: &c%player_health%
            &8▪ &6玩家身份: &c%luckperms_prefix%
            &8▪ &6玩家位置: &d%multiverse_world_alias%
            &r
            &6▶ &e点击联系OP
            &r
          suggest: '/msg %player_name% '
        - text: '&f%player_name%'
          hover: |-
            &r
            &8▪ &7延迟: &3%player_ping% Ms
            &8▪ &7血量: &c%player_health_rounded% ❤
            &8▪ &6玩家点卷: &a%playerpoints_points%
            &8▪ &6玩家金币: &a%cmi_user_balance%
            &8▪ &6玩家身份: &c%luckperms_prefix%
            &8▪ &6玩家位置: &d%multiverse_world_alias%
            &r
            &6▶ &e点击私聊
            &r
          suggest: '/msg %player_name% '
      part-before-msg:
        text: '&7: '
    suffix:
      example:
        text: ''
```

### Server environment

1.19.4群组服
子服purpur-1.19.4-1984.jar
群组：waterfall-1.19-535.jar
