### ISSUE TITLE
[问题]: 使用velocity入服聊天时控制台显示[Not secure] [新功能]:在trchat中使用内联语句

### ISSUE THREAD

**Issue by postyizhan** [FlickerProjects/TrChat#271]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.搭建并配置子服与velocity
2.入服打开聊天框进行聊天
3.切换后台 
![图片](https://github.com/TrPlugins/TrChat/assets/97342038/6f95f78e-1a2e-4429-8fbe-afb58619810c)

新功能 在trchat中使用内联语句

### 配置文件

```YAML
settings.yml

Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: VELOCITY

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```
Normal.yml
```
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&7'
      hover: '&7Date: %server_time_h:mm:ss a%'
    prefix:
      world:
        text: '&8[&3%player_world%&8]'
        hover: |-
          &r
          &8▪ &7Location: &3%player_world%&7, &2%player_x%/%player_y%/%player_z%
          &r
          &6▶ &eClick here to send a teleport request
          &r
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&4%player_name%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &r
            &6▶ &eClick to contact with op
            &r
          suggest: '/tell %player_name% '
        - text: '&7%player_name%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &r
            &6▶ &eClick to chat with me
            &r
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&7: '
    suffix:
      example:
        text: ''
```
```


### 日志

-

### 服务器环境

服务器版本:
1.20.1
插件列表:
Trchat
