### ISSUE TITLE
[issue]: 严重漏洞，变量替换漏洞

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#272]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

当使用[Doghook](https://www.mcbbs.net/thread-1105212-1-1.html)插件时，玩家发送的带变量的消息会被替换
玩家可以使用此漏洞通过checkitem变量给予/删除玩家的物品，也可以实现查看IP等功能，并且functions内用正则表达式匹配%%包裹的文本没有任何用处，trchat根本就不识别任何包含%的文本

### configuration file

```YAML
noplaceholder:
    pattern: '\%(.+)?\%'
    display:
      text: '&8&l[&c&l-&8&l]'
```

### Server environment

Server version:
...
Plugin list:
...

**Comment by ItsFlicker** [comment]
替换问题无法修复
[2.0.2](https://github.com/TrPlugins/TrChat/actions/runs/5607704796)修复了function替换

**Comment by Clexus** [comment]
> 替换问题无法修复 [2.0.2](https://github.com/TrPlugins/TrChat/actions/runs/5607704796)修复了function替换

![image](https://github.com/TrPlugins/TrChat/assets/62130504/27f732af-6d92-4e9e-b0a0-1b5ec8242030)
```
noplaceholder:
    pattern: '%\w+%'
    display:
      text: '&8&l[&c&l-&8&l]'
```
