### ISSUE TITLE
[issue] 

### ISSUE THREAD

**Issue by SnowballXueQiu** [FlickerProjects/TrChat#273]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

As soon as you enter text in the chat box you get an error as shown in Log

### configuration file

```YAML
yml
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: ''
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0
  Cooldown: '0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```
```


### logs

``` logs
[Server] [21:12:50] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.2
[Server] java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.HoverEvent.<init>(Lnet/md_5/bungee/api/chat/HoverEvent$Action;[Lnet/md_5/bungee/api/chat/hover/content/Content;)V
[Server]        at me.arasple.mc.trchat.taboolib.module.chat.impl.DefaultComponent.hoverText(DefaultComponent.kt:129) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.module.chat.impl.DefaultComponent.hoverText(DefaultComponent.kt:123) ~[?:?]
[Server]        at me.arasple.mc.trchat.module.display.format.obj.Style$Hover$Text.process(Style.kt:34) ~[?:?]
[Server]        at me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:101) ~[?:?]
[Server]        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:23) ~[?:?]
[Server]        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:135) ~[?:?]
[Server]        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:47) ~[?:?]
[Server]        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_362]
[Server]        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
[Server]        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
[Server]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-]
[Server]        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) ~[SimplePluginManager.class:git-CatServer-1.12.2-]
[Server]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[SimplePluginManager.class:git-CatServer-1.12.2-]
[Server]        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1530) ~[pa.class:?]
[Server]        at catserver.server.threads.AsyncChatThread.lambda$chat$0(AsyncChatThread.java:23) ~[AsyncChatThread.class:git-CatServer-1.12.2-]
[Server]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
[Server]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
[Server]        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
```

### Server environment

Server version:
Catserver 1.12.2
Plugin list:
LuckPerms, WorldEdit, PlaceholderAPI, NoSpawn, PluginManager, CMILib, VastseaLevel, HolographicDisplays, ConsoleSpamFix, ProtocolLib, TwkBezierTemplate, CustomSpawn, AyCore, LiteSignIn, UserPrefix, TrChat, PlayerIP, NBTAPI, Vault, DKCoins, GameModeAlias, LavaLocationManager, SbPlaceholder, BKCommonLib, LightCleaner, CMI, TrMenu, Citizens, Residence, TAB
