### ISSUE TITLE
[问题] sqlite 抛错

### ISSUE THREAD

**Issue by SakuraTao2007** [FlickerProjects/TrChat#279]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

初次使用，刚放上服务器后重启加载就出现报错

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32766

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trchat
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

![image](https://github.com/TrPlugins/TrChat/assets/59493751/540429c7-e3e5-46d5-9087-b2d2b3c9d198)

### 服务器环境

服务器版本:
paper-1.8.8
插件列表:
![image](https://github.com/TrPlugins/TrChat/assets/59493751/7c1da36a-d9cb-4133-84ad-3175f93ce40d)
