### ISSUE TITLE
[功能] 为functions的自定义功能添加执行动作功能，和请求为默认功能如@执行kether动作添加事例

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#281]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

```
1. 例如，当检测到输入QQ号时，撤回消息/执行kether动作
2. 默认的@功能下的actions我试过很多种写法都没有执行成功，能否提供事例到wiki中？
```

**Comment by ItsFlicker** [comment]
配置文件写错了，应该是Action

**Comment by ItsFlicker** [comment]
```yaml
hidePhoneNumber:
    pattern: '((13[0-9])|(14[0-9])|(15[0-9])|(17[0-9])|(18[0-9]))\d{8}'
    display:
      text: '&8[&c&m-&8]'
      hover:
        - '&7该内容疑似为手机号码,'
        - '&7已自动屏蔽隐藏.'
        - ''
        - '&8[&c!&8] &7请勿分享任何隐私信息'
    action: |-
      tell "你不能发送手机号码"
      cancel
```
```yaml
Item-Show:
    Enabled: true
    Permission: 'none'
    Cooldown: '30s'
    Origin-Name: false
    Compatible: false
    Keys:
      - "%i%"
      - "%i"
      - "%item%"
      - "%item"
      - "[i]"
      - "[item]"
    Action: |-
      if player op then {
        tell "你展示了你的物品"
      }
```
