### ISSUE TITLE
[问题] 跨服空手展示物品可导致其他玩家被踢出

### ISSUE THREAD

**Issue by DreamUniverse843** [FlickerProjects/TrChat#282]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

展示物品发起者位于 1.16.5 服务器内。
群组服子服共有 1.8.8，1.16.5，1.19.2 三个版本，所有玩家均被踢出，提示信息均如图。

1.手中不持任何物品，如图
![image](https://github.com/TrPlugins/TrChat/assets/53889721/60f78927-3fb0-4ae3-80fa-30cb54693591)
2.输入[i]
3.在服的所有玩家被踢出游戏，若为跨服则所有相连的玩家均会被踢出

客户端如下显示，服务端显示为 [Air x1]
![L4ZV1`}ETMQ9%XH1J@V9NIF](https://github.com/TrPlugins/TrChat/assets/53889721/409704ea-d832-498a-92f8-a4ec847ed3fa)
![UZ59EKSHFBZ_Q8~(Y2VVQ](https://github.com/TrPlugins/TrChat/assets/53889721/8f72091f-037c-4ab8-a979-11925f2ddd12)

### 配置文件

```YAML
Options:
  Speak-Condition: ''
  Proxy: true
  Force-Proxy: true
  Double-Transfer: false
  Auto-Join: true

Bindings:
  Prefix: ['!all']
  Command: []

Formats:
  - condition: null
    prefix:
      server:
        text: '&8[&3生存服&8] '
        hover: |-
          &7服务器名称 &3生存服
          &r
          &7版本号: &6%server_version%
          &7在线数: &a%server_online%&7/&2%server_max_players%
          &7TPS: &b%server_tps%
      player:
        text: '&e§6[§c%luckperms_prefix%§6] &f%player_name%: '
    msg:
      default-color: 'f'
      hover: '&7发送时间: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&e服务器&8: '
    msg:
      default-color: 'l'
```

### 日志

服务端无错误日志

客户端被踢出游戏，提示如图
![UZ59EKSHFBZ_Q8~(Y2VVQ](https://github.com/TrPlugins/TrChat/assets/53889721/ce1ebc29-26da-44d4-ab02-39a7b6d0d16b)

### 服务器环境

服务器版本:
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
插件列表:
Plugins (30): BetterRTP, ChestCommands, Chunky, CMI, CMILib, CoreProtect, CustomJoinItems*, DeluxeMenus, DeluxeTags, DieMessage, GoldenEnchants, KillNoDrop*, LiteBans, LuckPerms, Matrix, MiaoBoard, NexEngine, Orebfuscator, PlaceholderAPI, ProtocolLib, RealisticSeasons, Residence, TAB-Bridge, TrChat, UltimateTimber, Vault, ViaVersion, WorldEdit, WorldGuard, ZMusic-Addon
