### ISSUE TITLE
[严重bug] 多个玩家亲测，标签多的物品不能展示，只能展示标签少的东西，否则全服踢出

### ISSUE THREAD

**Issue by yedachang666** [FlickerProjects/TrChat#284]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

展示手中物品
标签多

### 配置文件

```YAML
General:
  Command-Controller:
    Enabled: true
    List:
      - 'arasple{exact: true}{condition: perm "trchat.admin"}'
      - 'ver(sion)?(s)?{condition: perm "trchat.admin"}'
      - 'help(s)?{condition: perm *trchat.admin}'
      - 'shout{cooldown: 3}'
  Mention:
    Enabled: true
    Self-Mention: true
    Permission: 'none'
    Cooldown: '30s'
    Notify: true
    Actions: [ ]
  Mention-All:
    Enabled: true
    Permission: 'trchat.function.mentionall'
    Cooldown: '5m'
    Notify: true
    Keys:
      - "@all"
      - "@everyone"
      - "@everybody"
      - "@所有人"
      - "@全体成员"
    Actions: [ ]
  Item-Show:
    Enabled: true
    Permission: 'none'
    Cooldown: '30s'
    Origin-Name: false
    Compatible: false
    Keys:
      - "%i%"
      - "%i"
      - "%1"
      - "$i"
      - "$1"
      - "%item%"
      - "%item"
      - "[炫耀]"
      - "[i]"
      - "[item]"
      - "@展示"
    Actions: [ ]
  Inventory-Show:
    Enabled: true
    Permission: 'none' #'trchat.function.inventoryshow'
    Cooldown: '30s'
    Keys:
      - '[inv]'
      - '[inventory]'
      - '展示背包'
    Actions: [ ]
  EnderChest-Show:
    Enabled: true
    Permission: 'none' #'trchat.function.enderchestshow'
    Cooldown: '30s'
    Keys:
      - '[ender]'
      - '[enderchest]'
      - '展示末影箱'
    Actions: [ ]
  Image-Show:
    Enabled: true
    Permission: 'trchat.function.imageshow'
    Cooldown: '1m'
    Key: '!\[([^;]*)\]\(([a-zA-Z]+://[^\s]*)\)'
    Actions: [ ]
Custom:
  # 示例 —— 网站分享
  shareUrl:
    pattern: '((https|http|ftp|rtsp|mms)?:\/\/)[^\s]+'
    display:
      text: '&8[&f&l网站&8]'
      hover:
        - ''
        - '&3网站: {0}'
        - ''
        - '&7点击进入!'
        - ''
        - '&8[&c!&8] &7谨防任何诈骗'
      url: '{0}'

  # 示例 —— QQ 分享
  shareQQ:
    condition: ~
    priority: 100
    # 匹配表达式
    # 示例模块的表达式部分来自互联网
    pattern: 'QQ( )?[1-9]([0-9]{5,11})'
    # 变量 {0} 是按下方表达式提取后的内容, 可以不配置此项
    text-filter: '[1-9]([0-9]{5,11})'
    # 自定义显示 JSON 组件
    display:
      text: '&8[&3&lQQ&8]'
      hover:
        - ''
        - '&3QQ: &b{0}'
        - ''
        - '&7这是一个 QQ 账号,'
        - '&7你可以点击此项快速打开聊天'
        - ''
        - '&8[&c!&8] &7请勿进行任何金钱交易'
        - '&8[&c!&8] &7交友需谨慎'
      url: 'https://wpa.qq.com/msgrd?v=3&uin={0}&site=qq&menu=yes'

  # 示例 —— B站视频 分享
  shareBilibili:
    pattern: 'BV( )?.{10}'
    text-filter: '.{12}'
    # 自定义显示 JSON 组件
    display:
      text: '&8[&f&lBilibili&8]'
      hover:
        - ''
        - '&7这可能是一个 Bilibili 视频,'
        - '&7点击即可访问'
        - ''
        - '&3BV号: &b{0}'
      url: 'https://www.bilibili.com/video/{0}'

  # 示例 —— 防止玩家暴露、分享真实手机号
  hidePhoneNumber:
    pattern: '((13[0-9])|(14[0-9])|(15[0-9])|(17[0-9])|(18[0-9]))\d{8}'
    display:
      text: '&8[&c&m-&8]'
      hover:
        - '&7该内容疑似为手机号码,'
        - '&7已自动屏蔽隐藏.'
        - ''
        - '&8[&c!&8] &7请勿分享任何隐私信息'

  # 示例 —— 隐藏身份证
  hideIDCardNumber:
    pattern: '([1-9]\d{5}[12]\d{3}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])\d{3}[0-9xX])'
    display:
      text: '&8[&c&m-&8]'
      hover:
        - '&7该内容疑似为身份证号,'
        - '&7已自动屏蔽隐藏.'
        - ''
        - '&8[&c!&8] &7请勿分享任何隐私信息'
        - '&7严重者可能处于禁言/封禁'

  # 示例 —— 高亮 IP
  glowIP:
    pattern: '(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)'
    display:
      text: '&e&n{0}'
      hover:
        - '&7这是一个 IP地址'
        - '&7点击复制!'
      copy: '{0}'

  # 示例 —— 高亮邮箱
  glowEmail:
    pattern: '\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}'
    display:
      text: '&e&n{0}'
      hover:
        - '&7这是一个邮箱'
        - '&7点击复制!'
      copy: '{0}'
```

### 日志

[14:27:01 INFO]: [龙之时装] 已更新玩家<taimeng>的 8 件时装: [皮卡丘鞋子, 皮卡丘头套, 皮卡丘衣服, 冰火翅膀, 我不是应急食品, 彩色背环, 阿莫斯之弓, 皮卡丘裤子]
[14:27:01 INFO]: [BanItem] 玩家 taimeng 拥有免检查权限,跳过检查背包
[14:27:01 INFO]: [DragonEdit] 重载成功
[14:27:02 INFO]: [DragonEdit] 检测配置 2023-06-27 18.35.05.yml 变动,已自动重载
[14:27:02 INFO]: [龙之时装] 已更新玩家<herobrine>的 0 件时装: []
[14:27:02 INFO]: [龙之时装] 已更新玩家<taimeng>的 8 件时装: [皮卡丘鞋子, 皮卡丘头套, 皮卡丘衣服, 冰火翅膀, 我不是应急食品, 彩色背环, 阿莫斯之弓, 皮卡丘裤子]
[14:27:02 INFO]: [BanItem] 检查了玩家 herobrine 的 1 个背包
[14:27:02 INFO]: [BanItem] 未发现任何禁用物品
[14:27:02 INFO]: [龙之时装] 已更新玩家<herobrine>的 0 件时装: []
[14:27:05 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 34517 bytes encoded, max 32767)
[14:27:05 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 34517 bytes encoded, max 32767)
[14:27:05 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 34517 bytes encoded, max 32767)
[14:27:05 INFO]: [十级魂力III]<taimeng> %i
[14:27:05 INFO]: ruo lost connection: Disconnected
[14:27:05 INFO]: [-] 玩家 ruo 休息一会
[14:27:05 INFO]: taimeng lost connection: Disconnected
[14:27:05 INFO]: [-] 玩家 taimeng 休息一会
[14:27:05 INFO]: herobrine lost connection: Disconnected
[14:27:05 INFO]: [-] 玩家 herobrine 休息一会
[14:27:05 INFO]: [云起之乡] 成功保存 herobrine 邮件数据
[14:27:05 INFO]: [云起之乡] 成功保存 taimeng 邮件数据
[14:27:05 INFO]: [云起之乡] 成功保存 ruo 邮件数据

### 服务器环境

服务器版本:spigot 1.12
...
插件列表:
...
SpawnProtected, PlaceholderAPI, Stp, XY-WorldNotInteract, RandomForge, PlugMan, ConsoleSpamFix, GuoItemLoreCommand, SuperBind, TrChat, MC17Pay, KeepInvandEXP, BanItem, ZH-Trash, TabooLines, AntiCraft, EpicPluginLib, NBTAPI, PlayMoreSounds, LuckPerms, DCJoinMessage, OpenInv, PacketListenerApi, AgarthaLib, CMILib, HuaEngine, GlowAPI, WorldBorder, MessageAnnouncer, ScriptManager, ProtocolLib, DeathMessagesPrime, MCCore, LibsDisguises, DropEffect, AutoRespawnPlus, Notbuild, FastAsyncWorldEdit, iConomy, SQLibrary, LangUtils, GlobalShop, JulyLibrary, Vault, EastLandLog4jFixer, CrazyCrates, SbPlaceholder, NeverLag, TabooLib, HolographicDisplays, PlayerPoints, AsyncKeepAlive, SkillAPI, CustomShop, EpicCraftingsPlus, ItemDrop, WorldEdit, Essentials, PointLogger, ColorMOTD, Sell, EffectLimit, TrMenu, TradeMe, TAB, JulyGuild, ScriptBlockPlus, PvpTitles, PlotSquared, WorldGuard, EssentialsProtect, Multiverse-Core, Citizens, Shopkeepers, CitizensCMD, Multiverse-Patches, MythicMobs, APBossBar, MythicMobsExtension, Adyeshach, Chemdah, AttributePlus, DungeonPlus, DragonArmourers, MythicArtifacts, MonsterAPI, DragonGPS, RuomoeCore, AttributeMM, AttributeCompatibleAPI, DragonCore, DragonInventory, Legendinlay, DragonActivity, StarLibrary, RuomoeSoulRing, ProxyGrade, StarAnalyze, StarCrate, StarShop, StarKit, TarotSoulMate, StarTitlePro, StarMaker, StarRide, StarPass, StarHOF, StarTraders, DsForgeReset, StarEnhance, StarTeam, StarEmailPlus, DragonEdit, StarTaskView, StarTeacher
