### ISSUE TITLE
[问题] 当前最新版本的 default-color 不再支持 RGB-Color

### ISSUE THREAD

**Issue by Azrael070** [FlickerProjects/TrChat#286]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

当我将 TrChat 2.0.0 PRE-35 更新到现在最新的 2.0.2 版本时，聊天频道格式内 default-color 选项无法再设置为 RGB 颜色，会无法解析并以正常字符显示，只能使用原版默认的颜色代码

### 配置文件

```YAML
Formats:
  - condition: ~
    msg:
      default-color: '#FFF8DC'
# 其他部分省略
```

### 日志

无

### 服务器环境

服务器版本: 1.18.2（Purpur）
...
插件列表:
...
