### ISSUE TITLE
PVPtitles导致展示武器全服人崩溃

### ISSUE THREAD

**Issue by yedachang666** [FlickerProjects/TrChat#296]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

经测试，pvptitles插件卸载后无异常

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: NONE
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 35000

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[14:49:50 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 34688 bytes encoded, max 32767)
[14:49:50 INFO]: [十级魂力III]<ydc> %i
[14:49:50 INFO]: ydc lost connection: Disconnected

### 服务器环境

服务器版本:
...1.12
插件列表:
...
SpawnProtected, PlaceholderAPI, Stp, XY-WorldNotInteract, PlugMan, ConsoleSpamFix, GuoItemLoreCommand, TrChat, MC17Pay, KeepInvandEXP, BanItem, ZH-Trash, TabooLines, AntiCraft, EpicPluginLib, NBTAPI, PlayMoreSounds, LuckPerms, OpenInv, PacketListenerApi, AgarthaLib, CMILib, HuaEngine, GlowAPI, WorldBorder, MessageAnnouncer, ScriptManager, ProtocolLib, DeathMessagesPrime, MCCore, LibsDisguises, DropEffect, CpsCheck, AutoRespawnPlus, Notbuild, FastAsyncWorldEdit, iConomy, SQLibrary, LangUtils, GlobalShop, JulyLibrary, Vault, EastLandLog4jFixer, CrazyCrates, SbPlaceholder, NeverLag, TabooLib, HolographicDisplays, PlayerPoints, AsyncKeepAlive, CustomShop, DreamBind, EpicCraftingsPlus, ItemDrop, WorldEdit, Essentials, PointLogger, ColorMOTD, Sell, EffectLimit, Citizens, TAB, JulyGuild, ScriptBlockPlus, PlotSquared, CitizensCMD, EssentialsProtect, Multiverse-Core, Shopkeepers, Multiverse-Patches, MythicMobs, APBossBar, MythicMobsExtension, AttributePlus, DungeonPlus, Legendinlay, DragonArmourers, MythicArtifacts, MonsterAPI, AttributeMM, AttributeCompatibleAPI, DragonInventory
