### ISSUE TITLE
[问题] 私聊频道内聊天可被Dynmap看见

### ISSUE THREAD

**Issue by Shizuri23** [FlickerProjects/TrChat#298]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1️⃣/m 玩家
<img width="351" alt="image" src="https://github.com/TrPlugins/TrChat/assets/46082179/41ac5fee-3fe7-49b7-844f-a498aa49bed5">
2️⃣说话
<img width="309" alt="image" src="https://github.com/TrPlugins/TrChat/assets/46082179/78ddf010-1148-433b-bc88-6e5bd33a58eb">
3️⃣去Dynmap查看
<img width="360" alt="image" src="https://github.com/TrPlugins/TrChat/assets/46082179/e5cecffd-9422-4360-b8c4-944f66664409">
可以看见私密通话的聊天内容

### 配置文件

```YAML
Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Sender:
  - prefix:
      sender:
        text: '&8[&a%player_name% &7➦ %trchat_toplayer%&3&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&8[&6%player_name% &7➥ &2%trchat_toplayer%&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'
```

### 服务器环境

服务器版本:
This server is running Leaves version git-Leaves-"31672c1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 31672c1)
You are 3 version(s) behind
Download the new version at: https://leavesmc.top/downloads/leaves
Previous version: git-Leaves-"66b078c" (MC: 1.20.1)
插件列表:
<img width="613" alt="image" src="https://github.com/TrPlugins/TrChat/assets/46082179/5fbd8083-e80e-4597-a2dd-136e8721b71f">
