### ISSUE TITLE
[问题] 玩家说话导致然后报错

### ISSUE THREAD

**Issue by jhqwqmc** [FlickerProjects/TrChat#299]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

玩家在聊天栏聊天

### 配置文件

```YAML
Options:
  Check-Update: false
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32766
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Global'

Database:
  Method: SQL
  SQL:
    host: localhost
    port: 3306
    user: trchat
    password: wlm245235039
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[01:18:30 WARN]: java.lang.NoClassDefFoundError: net/minecraft/network/protocol/game/ClientboundCustomChatCompletionsPacket$Action
[01:18:30 WARN]:        at me.arasple.mc.trchat.api.nms.NMSImpl.removeCustomChatCompletions(NMSImpl.kt:120)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$RedisSide.execute(BukkitProxyProcessor.kt:244)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:46)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:168)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:144)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:140)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec$expansion_alkaid_redis(SingleRedisConnection.kt:39)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda-2(SingleRedisConnection.kt:140)
[01:18:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:18:30 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:18:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:18:30 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ClientboundCustomChatCompletionsPacket$Action
[01:18:30 WARN]:        ... 17 more
[01:18:30 WARN]: java.lang.NoClassDefFoundError: net/minecraft/network/protocol/game/ClientboundCustomChatCompletionsPacket$Action
[01:18:30 WARN]:        at me.arasple.mc.trchat.api.nms.NMSImpl.removeCustomChatCompletions(NMSImpl.kt:120)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$RedisSide.execute(BukkitProxyProcessor.kt:244)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:46)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:168)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:144)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:140)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec$expansion_alkaid_redis(SingleRedisConnection.kt:39)
[01:18:30 WARN]:        at [T][聊天]TrChat-2.0.4.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda-2(SingleRedisConnection.kt:140)
[01:18:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[01:18:30 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:18:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:18:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:18:30 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.ClientboundCustomChatCompletionsPacket$Action
[01:18:30 WARN]:        ... 17 more

### 服务器环境

服务器版本:
purpur-1913
