### ISSUE TITLE
[问题] 告示牌不允许字符 '[' 和 ']'

### ISSUE THREAD

**Issue by TheFloodDragon** [FlickerProjects/TrChat#300]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

只要在告示牌内输入 `[` 或者 `]`
都会被清除（直接消失）
无论成不成对
这会影响到部分插件的使用（如CMI）
其他字符暂未发现有类似情况

### 配置文件

```YAML
Enable:
  Chat: true
  Sign: true
  Anvil: true
  Item: false

Cloud-Thesaurus:
  Enabled: true
  Ignored: ['nt']
  Urls:
    - 'https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json' # 感谢南城提供的词库

Local:
  - 'NMSL'
  - 'fuck'
  - 'shit'

Ignored-Punctuations: ['!','.',',','#','$','%','&','*','(',')','|','?','/','@','"','\',';','[',']','{','}','+','~','-','_','=','^','<','>',' ','　','！','。','，','￥','（','）','？','、','“','‘','；','【','】','——','……','《','》','\\', '`']
WhiteList: ['has been']
Replacement: '*'
```
```

Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 100000
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: mrs_trchat
  SQL:
    host: localhost
    port: 3306
    user: root
    password: f8Ww32a76FpV
    database: tydb
    table: mrs_trchat

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

无后台日志

### 服务器环境

服务器版本: Paper 1.20.1
