### ISSUE TITLE
[问题] 在1.19.2Cardboard下无法使用TrChat跨服聊天

### ISSUE THREAD

**Issue by Mxmilu666** [FlickerProjects/TrChat#301]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

环境:1.19.2Cardboard
详细描述:
可以看见别的服务器的消息，但是在本服务器发送消息玩家无法看见。并在后台报错
注:Papi版本为2.10.3，高于此版本Papi会报错

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: VELOCITY
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data
  Mongodb:
    client: 'mongodb://localhost:3307'
    database: trixey
    collection: chat

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Global'
```

### 日志

https://pastebin.ubuntu.com/p/8k5sZPgdBV/

### 服务器环境

服务器版本:
This server is running Cardboard version git-f56d9b9 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1
-SNAPSHOT) (Git: null on null)
插件列表:
Plugins (2): PlaceholderAPI, TrChat
Mod列表:
Mods: Cardboard, Carpet Mod, toml4j, Fabric API, Fabric Loader, FabricProxy Lite, iCommonLib 1.19,
 Minecraft
