### ISSUE TITLE
[问题] /ignore 指令无效

### ISSUE THREAD

**Issue by konglingmingkong** [FlickerProjects/TrChat#306]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

/ignore 指令无效
输入指令没任何反馈
也没效果

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  Check-Update: false
Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.99
  Cooldown: '1.0s'
  Length-Limit: 200

Color:
  Chat: false
  Sign: false
  Anvil: false
  Book: false

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本:
1.20
插件列表:
2.0.4
