### ISSUE TITLE
[问题] ignore指令无效  Component-Max-Length如果跨服无效

### ISSUE THREAD

**Issue by konglingmingkong** [FlickerProjects/TrChat#307]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.   ignore指令无效
指令输入后提示已经屏蔽玩家  ignorelist查询不到 实际也没有屏蔽
![image](https://github.com/TrPlugins/TrChat/assets/50398407/e3da0aed-65c0-4b97-8d81-ade7365d6519)

2.
![image](https://github.com/TrPlugins/TrChat/assets/50398407/b9091cbf-4859-4b9a-ba22-4e8a34d9de64)
设置里面Component-Max-Length是52700，测试发现单服设置有效，如果跨服这个设置无效。所有子服已经都设置52700了
BC里面没相关设置

### 配置文件

```YAML
Options:
  Check-Update: false
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 52700
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.99
  Cooldown: '1.0s'
  Length-Limit: 200

Color:
  Chat: false
  Sign: true
  Anvil: false
  Book: false
```

### 服务器环境

服务器版本:
1.20
插件列表:
2.0.5
