### ISSUE TITLE
[i]输出的结果点击后出现的物品可以拿取

### ISSUE THREAD

**Issue by ushion0a** [FlickerProjects/TrChat#308]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.拿一个物品
2.在聊天框输入[i]
3.在聊天栏里点击发出来的物品详情

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '1.7s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 服务器环境

服务器版本:
This server is running CraftBukkit version 3856-Spigot-94e187b-b76ceb4 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
插件列表:
Plugins (73): PlaceholderAPI, Back, BotSentry, HolographicDisplays, EClean, ChatAsUser, NoteBlockAPI, NoChatReports, ViaVersion, NBTAPI, ViaBackwards, LuckPerms, OpenInv, CMILib, MiniAnnouncement, AnCDK, LoneLibs, ProtocolLib, LiteSignIn, Snow-BetterRTP, MiaoBoard, floodgate, Vault, Lores, ViaRewind, ImageFrame, ShadowCore, Marriage, MusicBox, SkinsRestorer, Themis, Orebfuscator, Geyser-Spigot, WkKit, NexEngine, LagAssist, dynmap, WorldEdit, Essentials, GrimAC, ItemEdit, Multiverse-Core, CrossplatForms, TAB, PlayerPoints, CombatPets, WorldGuard, BossShopPro, EssentialsSpawn, CoreProtect, GeekRewardPlus, ServerlistMOTD, Citizens, Shopkeepers, Residence, PlayerParticles, EliteMobs, AuthMe, HoloMobHealth, QuickShop, EntityDetection, CitizensCMD, PlayerTitle, PlayerGuild, Skript, ItemsAdder, ChestCommands, TrChat, AdvancedKits, EvenMoreFish, GeekCosmetics, GeekMail-Pro, PlugManX (PlugMan)

**Comment by ItsFlicker** [comment]
背包和末影箱展示是否可以拿取?

**Comment by ushion0a** [comment]
> 背包和末影箱展示是否可以拿取?

还没有尝试

**Comment by ItsFlicker** [comment]
只装papi和trchat的paper端无法复现

**Comment by McAZero** [comment]
CatServer version 1.16.5-98eabb0e
arclight-1.18.2-1.0.9-7a0a194
复现

**Comment by ItsFlicker** [comment]
不知道如何修复，但是加入了是否显示界面的选项
```yaml
  Item-Show:
    Enabled: true
    Permission: 'none'
    Cooldown: '30s'
    Origin-Name: false
    Compatible: false
    UI: true
    Keys:
      - "%i%"
      - "%i"
      - "%item%"
      - "%item"
      - "[i]"
      - "[item]"
    Action: [ ]
```
