### ISSUE TITLE
[问题] 无法聊天且后台报错

### ISSUE THREAD

**Issue by L1-An** [FlickerProjects/TrChat#309]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在游戏内发送聊天信息后无任何反应，但后台会显示玩家聊天内容且存在报错

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: true
  Component-Max-Length: 32766
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: false
  Sign: false
  Anvil: false
  Book: false
```

### 日志

[18:21:31] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.6
java.lang.IllegalStateException: Got an error translating component!Please report!
        at me.arasple.mc.trchat.api.nms.NMSImpl.craftChatMessageFromComponent(NMSImpl.kt:40) ~[?:?]
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendMessage(NMSImpl.kt:62) ~[?:?]
        at me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:67) ~[?:?]
        at me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:102) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:176) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:50) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1625) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1563) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(Ljava/lang/String;)Lnet/minecraft/server/v1_16_R1/IChatBaseComponent;
        at me.arasple.mc.trchat.api.nms.NMSImpl.craftChatMessageFromComponent(NMSImpl.kt:37) ~[?:?]
        ... 27 more
[18:21:31] [Async Chat Thread - #0/INFO]: <C1oudYAb> e

### 服务器环境

服务器版本:
[18:24:12] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[18:24:14] [Thread-11/INFO]: You are 52 version(s) behind
插件列表:
[18:24:39] [Server thread/INFO]: Plugins (5): ViaVersion, Vault, PlaceholderAPI, XConomy, TrChat
