### ISSUE TITLE
[问题] 

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#310]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

![8F7CA8DBD2DE934D8FFB79828E672E5E](https://github.com/TrPlugins/TrChat/assets/62130504/825d10ba-4ddb-4371-b84d-8b562fd8683a)

### 配置文件

```YAML
因为玩家名被屏蔽添加了wiki中的内容
Events:
  Process: |-
    filter get &message
```

### 服务器环境

服务器版本:
Paper-1.12-1618
插件列表:
