### ISSUE TITLE
[issue] 后台看不到玩家输入的消息

### ISSUE THREAD

**Issue by jhqwqmc** [FlickerProjects/TrChat#313]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

后台看不到玩家输入的消息

### configuration file

```YAML
settings.yml
'''
Options:
  Check-Update: false
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 999999999999
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Global'

Database:
  Method: SQL
  SQL:
    host: localhost
    port: 3306
    user: trchat
    password: xxxxxx
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
'''
Global.yml
'''
Options:
  Target: ALL
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&f'
      hover: '&7时间: %server_time_h:mm:ss a%'
    prefix:
      player:
        - text: '&7[&f%playerGuild_show_name%&7]&7 &f%playerTitle_use% &7%player_displayname% ▶ &f'
          hover: '&6▶ &e点击与我私聊'
          suggest: '/msg %player_name% '
'''
```

### Server environment

Server version:
git-Purpur-2036 (MC: 1.20.1)*
Plugin list:
[12:47:38 INFO]: Paper Plugins: (2):
[12:47:38 INFO]:  - EconomyShopGUI-Premium, HuskHomes
[12:47:38 INFO]: Bukkit Plugins: (123):
[12:47:38 INFO]:  - AdvancedAchievements, AdvancedCrates, AdvancedEnchantments, AdvancedWish, ajLeaderboards, ajParkour, *ajSpawnJoin, AntiGeyserPlayerUUID, AntiWorldFly, BattlePass
[12:47:38 INFO]:  BedrockChestUI, BetterProfiles, BookNews, BungeeGuard, ChestSort, Citizens, CitizensCMD, CMI, CMILib, ConsoleFilter
[12:47:38 INFO]:  CoreProtect, CrossplatForms, CtOnlineReward, CustomCrops, CustomFishing, CustomJoinAndQuitMessages, CustomNameplates, DecentHolograms, DeluxeMenus, DungeonParties
[12:47:38 INFO]:  ElytraLimit, EncRemover, EpicPluginLib, exppond, EZColors, *FallbackServerAddon, FastAsyncWorldEdit, FestiveFirework, floodgate, Floodgate-Skript
[12:47:38 INFO]:  FontStyleReplacer, FreedomChat, GadgetsMenu, GeyserHacks, GlobalMarketPlus, HolographicDisplays, *HotkeyCommand, HuskHomesGUI, Images, InfiniteJump
[12:47:38 INFO]:  InventoryRollbackPlus, InvSync, ItemJoin, ItemsAdder, Jobs, JPremium, Kudos, LibsDisguises, LightAPI, LiteBans
[12:47:38 INFO]:  LiteSignIn, *LiveRecorder, LoneLibs, LuckPerms, Matrix, mcMMO, McmmoGui, MinePay, MIReplacer, MMOCore
[12:47:38 INFO]:  MMOItems, MobsToEggs, Multiverse-Core, Multiverse-NetherPortals, MythicDungeons, MythicLib, MythicMobs, NBTAPI, NPC_Destinations, PartyAndFriendsGUI
[12:47:38 INFO]:  PL-Hide, PlaceholderAPI, Plan, PlayerCDK, PlayerGuild, PlayerParticles, PlayerPoints, PlayerTitle, PlayerWarp, PlugManX
[12:47:38 INFO]:  ProtocolLib, ProtocolStringReplacer, QuickShop, QuickShopForm, RealisticSeasons, RentIt, *ServerTutorialPlus, *ShieldDirtyRemake, Skript, Skript-Packet
[12:47:38 INFO]:  *skript-placeholders, skript-reflect, spark, TAB-Bridge, Themis, TigerReports, Tpa, TradeSystem, TrChat, TrElytra
[12:47:38 INFO]:  TrMenu, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, voicechat, VoidSpawn, WlmTrash, WorldBorder, WorldEditSelectionVisualizer
[12:47:38 INFO]:  WorldGuard, XConomy, ZMusic-Addon
