### ISSUE TITLE
[问题] /r 回复的行为在跨服务器时比较奇怪

### ISSUE THREAD

**Issue by MagmaBlock** [FlickerProjects/TrChat#314]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

Velocity 环境。接到的玩家反馈是：私聊跨服无法使用 /r 来回复。
这会测试，发现以下奇怪的情况：
* 都不在一个服务器，A 私聊 B，A 能通过 /r 回复，B 不能，且 B 在手动私聊 A 后还是不能 /r；
* 都不在一个服务器，A 私聊 B，A 能通过 /r 回复。A 又私聊 C，A 使用 /r，回复的还是 B；
* 在一个服务器，/r 工作正常。

同时，即使 /r 回复失败了，也缺少一个错误提示，打完指令就没了

### 配置文件

```YAML
Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w', 't']

Sender:
  - prefix:
      start:
        text: '&7['
      sender:
        text: '&f你'
      arrow:
        text: ' &7-> '
        hover: '&7发送于 &f%server_time_HH:mm:ss%'
      target:
        text: '&b%trchat_toplayer%'
        hover: '&f[点击与 %player_name% 私聊]'
        suggest: '/tell %player_name% '
      end: 
        text: '&7] '
    msg:
      default-color: 'f'

Receiver:
  - prefix:
      start:
        text: '&7['
      sender:
        text: '&b%player_name%'
        hover: '&f[点击与 %player_name% 私聊]'
        suggest: '/tell %player_name% '
      arrow:
        text: ' &7-> '
        hover: '&7发送于 &f%server_time_HH:mm:ss%'
      receiver:
        text: '&f你'
      end: 
        text: '&7] '
    msg:
      default-color: 'f'
```

### 服务器环境

服务器版本:
Velocity 3.2.0，子服都是 Paper 1.20.1
插件列表:
因为子服务器太多了就列出主要情况吧：子服用的是 CMI，聊天相关的指令已经收起，确定使用的是 TrChat 的 reply 和私聊；
Velocity 上只有 TrChat 是和聊天有关的。
