### ISSUE TITLE
[issue] 无法使用at 

### ISSUE THREAD

**Issue by Mc9420** [FlickerProjects/TrChat#319]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

自更新最新版本后无法使用at.
 at玩家功能失效 已尝试更换admin账户、重启服务器 均无效 

### configuration file

```YAML
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 1
    msg:
      default-color: '&f'
      hover: '&7Date: %server_time_h:mm:ss a%'
    prefix:
      player:
        - text: '%multiverse_world_alias% %vault_prefix%%player_displayname% %vault_suffix%'
          hover: |-
            &r
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &r
      part-before-msg:
        text: '&f: '
```

### logs

无报错

### Server environment

Server version: 1.12.2 PaperSpigot
...
Plugin list:
...
