### ISSUE TITLE
[问题] 屏蔽的词语被正常同步到了DiscordSRV

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#322]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 安装DiscordSRV与TrChat 并配置DiscordSRV同步
2. 输入TrChat屏蔽词 游戏内会被替换为默认的星号 Discord频道则正常显示屏蔽词

![bug](https://github.com/TrPlugins/TrChat/assets/81153017/5eaa8596-5f56-453b-88a6-14016e6dcebf)

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['vault']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator', 'DiscordSRV']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data
  Mongodb:
    client: 'mongodb://localhost:3307'
    database: trixey
    collection: chat

Chat:
  Anti-Repeat: 0.85
  Cooldown: '0.5s'
  Length-Limit: 150

Color:
  Chat: false
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'

除此之外均默认
```

### 服务器环境

服务器版本:
[21:49:46 INFO]: Checking version, please wait...
[21:49:48 INFO]: This server is running Paper version git-Paper-68 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5de0f8a)
You are 106 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
...
插件列表:
[21:50:18 INFO]: Server Plugins (15):
[21:50:18 INFO]: Paper Plugins:
[21:50:18 INFO]:  - HuskHomes
[21:50:18 INFO]: Bukkit Plugins:
[21:50:18 INFO]:  - Bank, CMI, CMILib, Core, DiscordSRV, GemsEconomy, PlaceholderAPI, qsaddon-list, qssuite-limited, QuickShop-Hikari
[21:50:18 INFO]:  ServerSelectorX, SSX-Connector, TrChat, Vault
...
