### ISSUE TITLE
[问题] @指定玩家功能不可用

### ISSUE THREAD

**Issue by BiliRumble** [FlickerProjects/TrChat#324]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 更新最新版本的 TrChat

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: BUNGEE

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '0.5s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

无报错/额外输出日志

### 服务器环境

服务器版本:
Spigot 1.20.1
插件列表:
Plugins (35): JoinCommands, CrazyAuctionsPlus, PlaceholderAPI, CMILib, PlugMan, LiteSignIn, TrChat, MiaoBoard, PVPMode, mcMMO, ViaVersion, NBTAPI, JulyLibrary, ViaBackwards, ViaRewind, LuckPerms, JulySafe, SkinsRestorer, Vault, GemsEconomy, ResourceWorld, UltiCore, PlayerPoints, Multiverse-Core, TrMenu, UltiTools, TrHologram, CMI, Citizens, Shopkeepers, Residence, QuickShop, AuthMe, DeluxeTags, CoreProtect
