### ISSUE TITLE
[issue] 

### ISSUE THREAD

**Issue by jhqwqmc** [FlickerProjects/TrChat#326]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

直接加载插件

### configuration file

```YAML
Options:
  Check-Update: false
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Global'

Database:
  Method: SQL
  SQL:
    host: localhost
    port: 3306
    user: root
    password: 12125L
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### logs

![image](https://github.com/TrPlugins/TrChat/assets/113768629/2444be0b-b61b-4fc1-8582-4653bf5e9f77)

### Server environment

Server version:
git-Paper-211 (MC: 1.19.2)
Plugin list:
7yPay*, AdvancedEnchantments, AureliumSkills, BetterStructures, CinematicStudio, Citizens, CitizensGUI, CMI, CMILib, ConsoleSpamFix, CoreProtect, CosmeticsCore, CustomFishing, CustomNameplates, DeluxeMenus, Denizen, eco, FastAsyncWorldEdit (WorldEdit), GeekRewardPlus, HuskHomes, HuskHomesGUI, InstantCommand, InvSync, ItemsAdder, Jobs, JoinAndLeaveDisabler*, JoinCommands, JulySafe, LevelledMobs, LibsDisguises, LiteSignIn, LoneLibs, LuckPerms, MagicGestures, Matrix, MCPets, MMOItems, ModelEngine, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, ODailyQuests, PixelRtp, PixelWorldPro, PlaceholderAPI, PlayerAuctions, PlayerGuild, PlayerPoints, PlayerProfile, PlayerWarp, PlugManX (PlugMan), ProtectionStones, ProtocolLib, QuickShop, RealisticSeasons, ShopGUIPlus, Skript, StatTrackers, TAB-Bridge, Terra, TrChat, UltimateTimber, Vault, VoidFramework-Bukkit, WorldBorder, WorldEdit, WorldGuard, XConomy
