### ISSUE TITLE
[问题] 屏蔽词问题

### ISSUE THREAD

**Issue by CutePlank233** [FlickerProjects/TrChat#327]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 设置屏蔽词，其中屏蔽词的字符串里包含重复字符（例如汉字 / 字母 / 数字）
2. 尝试发送
3. 会发现包含（一部分，数字 / 字母有的时候能复现有的时候不能，汉字则 100% 复现）重复字符的关键词，即使已经设置，屏蔽也无效（例如下图的配置文件，“齐齐哈尔”、“HTT”、“测试二二”、“45667899”都无法正常被屏蔽）

### 配置文件

```YAML
Enable:
  Chat: true
  Sign: true
  Anvil: true
  Item: false

Cloud-Thesaurus:
  Enabled: true
  Ignored: ['nt','maintown']
  Urls:
    - 'https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json' # 感谢南城提供的词库

Local:
#不友好主播反制名单中的主播
  - '淩钰'
  - '凌钰'
  - '忘川的涟漪'
  - '岑悼秋'
  - '悼秋'
  - '涟'
  - '漪'
  - '殷子瀛'
  - '子瀛'
  - '临安'
  - '七咔拉'
  - '七咔啦'
  - '七宝'
  - '7宝'
  - '柠溪'
  - 'HTT'
  - '神海'
  - '逍遥'
#（此处省略一堆）
  - 'lian'
  - 'yi'
#不友善词语
  - '张京华'
  - '蛋'
  - '瓜'
  - '专栏'
  - '挂人'
  - '网暴'
  - '毕业'
  - '转生'
  - '掉粉'
  - 'coser'
  - '哈尔滨'
  - '齐齐哈尔'
  - '动漫展'
  - '漫展'
  - '展子'
  - '裙底'
  - '裙'
  - '文杰'
  - '动漫社'
  - '妹子'
#可能不适宜的内容
  - '倒闭'
  - '拉黑'
  - '隐私设置'
  - '黑名单'
  - '屏蔽'
  - '网易'
  - '冈易'
  - '禁言'
  - '超管'
  - '陈睿'
  - '删号'
  - '转生'
  - '退群'
  - '删好友'
#攻击性词语
  - '答辩'
  - '伞兵'
#关于某个网络暴力团伙的常用恶搞词汇
#（此处省略一堆）
#其他
#临时措施
  - '测试一'
  - '测试二二'
  - '12345678'
  - '45667899'
  

Ignored-Punctuations: []
WhiteList: ['has been']
Replacement: '*'
```

### 服务器环境

服务器版本:
This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are 62 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-794 (MC: 1.16.5)

插件列表:
Plugins (26): BetterKeepInventory, CMILib, CoreProtect, DeluxeTags, FastAsyncWorldEdit (WorldEdit), GroupManager, Ip2region, Law, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NexEngine, PlaceholderAPI, ProtocolLib, QuickShop, Residence, SkinsRestorer, SkipSleep, SunLight, TrChat, TrMenu, Vault, ViaBackwards, ViaVersion, WorldProtecion, XConomy
