### ISSUE TITLE
聊天信息验证失败（文档中方法无效）

### ISSUE THREAD

**Issue by LangZongz** [FlickerProjects/TrChat#332]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.使用paper1.20.1版本服务端
2.安装trchat 2.0.8，placeholderapi 2.11.5
3.关闭正版验证且关闭enforce-secure-profile
4.游戏内输入/say xxxxxx
5.提示聊天信息验证失败，玩家被踢出
![image](https://github.com/TrPlugins/TrChat/assets/129711891/c885da5b-5fa9-4f37-9a0d-ac62374e5f51)

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

无报错
经过测试发现：
1.开启正版验证时无此问题
2.关闭正版验证时，无论enforce-secure-profile是否开启，均有此问题
3.仅安装trchat和placeholderapi即会出现此问题

### 服务器环境

服务器版本:
git-Paper-196 (MC: 1.20.1) 
插件列表:
trchat 2.0.8
papi 2.11.5
