### ISSUE TITLE
[问题] minimessage格式问题

### ISSUE THREAD

**Issue by jhqwqmc** [FlickerProjects/TrChat#333]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

在使用minimessage时会有格式问题，希望可以修改成标准格式
这是trchat的展示：![image](https://github.com/TrPlugins/TrChat/assets/113768629/bbcbbae3-bc86-46d3-a8b1-3bbf68465fb8)
这是tab的展示：![image](https://github.com/TrPlugins/TrChat/assets/113768629/2a813ddd-2712-4c75-909b-6fa28e491d2f)
这是minimessage：<gradient:#41F0CF:#F1AF9A>鸡你太美</gradient>

### 配置文件

```YAML
Options:
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Formats:
  - condition: null
    prefix:
      playertitle:
        text: '&7&3%luckperms_prefix%&7 '
        hover: |-
          &e%player_name%的信息
          &d称号数量 &7>> &f%playerTitle_number%
      playerguild: 
        text: '&3%changeoutput_ignorecolor_input:{playerGuild_show_name}_matcher:无公会_ifmatch:_else:{playerGuild_show_name} %'
        hover: |-
          &e%player_name%的信息
          &d公会职务 &7>> &f%playerGuild_role%
          &d公会贡献 &7>> &f%playerGuild_money%
      player:
        text: '&f%player_name%'
        hover: |-
          &3点我查看对方详细信息
        command: '/playerprofile %player_name%'
      end:
        text: ' &8>>> '
    msg:
      default-color: 'f'
      hover: '&7发送时间: %server_time_HH:mm:ss%'
```

### 服务器环境

服务器版本:
git-Purpur-2062 (MC: 1.20.1)
插件列表:
BKCommonLib, HuskHomes, AdvancedAchievements, AdvancedEnchantments, AngelChest, AntiPopup, AureliumSkills, BattlePass, BetterRTP, BetterStructures, BiliBiliToper, ChestProtect, ChestSort, Citizens, CitizensCMD, CMI, CMILib, CompatNoCheatPlus, CoreProtect, CustomNameplates, DeluxeMenus, EliteMobs, EncRemover, FastAsyncWorldEdit, GlobalMarketPlus, GSit, HeadDatabase, HiveChecker, HuskHomesGUI, InvSync, Iris, ItemJoin, ItemsAdder, JPremium, LiteBans, LoneLibs, LuckPerms, MagicCosmetics, MCPets, MMOCore, ModelEngine, MotionCapture, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, NoCheatPlus, Pl-Hide-Pro, PlaceholderAPI, PlayerGuild, PlayerParticles, PlayerPoints, PlayerProfile, PlayerTitle, PlayerWarp, PlugManX, PremiumVanish, ProtocolLib, ProtocolStringReplacer, RayTraceAntiXray, RealisticSeasons, SkinsRestorer, spark, TAB-Bridge, TrChat, UltimateTimber, UseTranslatedNames, Vault, ViaBackwards, ViaVersion, VoidSpawn, Vulcan, WlmTrash, WorldBorder, WorldGuard, *WTF, XConomy, ZMusic-Addon
