### ISSUE TITLE
[问题] 私聊无法使用CMI昵称名

### ISSUE THREAD

**Issue by gyc123456-1** [FlickerProjects/TrChat#338]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.用cmi的nick指令设置昵称
2.用私聊指令私聊昵称名

### 配置文件

```YAML
Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Events:
  Process: |-
    filter get &message

Sender:
  - prefix:
      sender:
        text: '&5[%player_displayname% &5➦ %trchat_toplayer%&5] '
    msg:
      default-color: 'f'
      hover: '&7时间: %server_time_HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&5[%player_displayname% &5➥ %trchat_toplayer%&5] '
    msg:
      default-color: 'f'
      hover: '&7时间: %server_time_HH:mm:ss%'
```

### 日志

![image](https://github.com/TrPlugins/TrChat/assets/69791212/600e874f-41fd-469f-a008-d5effd342e85)

### 服务器环境

服务器版本:
Paper(196) 1.20.1-R0.1-SNAPSHOT+
插件列表:
[08:55:27 INFO]: Server Plugins (103):
[08:55:27 INFO]: Paper Plugins:
[08:55:27 INFO]:  - eco
[08:55:27 INFO]: Bukkit Plugins:
[08:55:27 INFO]:  - Admin-GUI, AdvancedBan, AifadianPay, AttributePlus, AureliumSkills, BanIt, BetterReactor, BlockLocker, ChestCommands, Citizens
[08:55:27 INFO]:  *ClearEntity, CMI, *CMIEInjector, CMILib, Coins, *CompatNoCheatPlus, ConsoleSpamFix, ControlPlayer, CoreProtect, CrazyAuctionsPlus
[08:55:27 INFO]:  CustomBiologyDrop1.20.1, CustomFishing, DamageIndicator, DeEnchantment, DyedBackpacks, EcoPower, ElectricSpawners, EnderDragon, ExoticGarden, FoxyMachines
[08:55:27 INFO]:  GardenBank, GuizhanLibPlugin, HardcoreSlimefun, HolographicDisplays, HotbarPets, HyronicFriends, *ia_upload, Images, ItemCommand, ItemsAdder
[08:55:27 INFO]:  ItemsAdder-WorldEdit, LibsDisguises, LiteSignIn, LiteXpansion, LoneLibs, *Lore, LPX, LuckPerms, MobCapturer, monster
[08:55:27 INFO]:  MultiLogin, Multiverse-Core, NBTAPI, Networks, NoCheatPlus, OpenInv, ParticleLib, PistonMOTD, PlaceholderAPI, Plan
[08:55:27 INFO]:  PlayerGuild, PlayerIntensify, PlayerPoints, PlayerTitle, PlayerWarp, PlugMan, PotionExpansion, PrivateStorage, ProtocolLib, ProtocolStringReplacer
[08:55:27 INFO]:  PublicBin, QuickShop, RecipeControl, Residence, ServerBooster, SFCalc, Skulls, Slimefun, SlimefunOreChunks, SlimeGlue
[08:55:27 INFO]:  SlimeSec, SlimeTinker, SlimyTreeTaps, *SuperBan, TAB, TileDataSaver, TradeMe, TrChat, TrollingFreedom, UltimateAntiBot
[08:55:27 INFO]:  UltimateGenerators, UpgradeableHoppers, UseTranslatedNames, Vault, Vegas, ViaBackwards, ViaVersion, VipSystem, WhatIsThis, WorldEdit
[08:55:27 INFO]:  XgpLottery, YukiNoaAPI
