### ISSUE TITLE
[问题] function 屏蔽问题

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#346]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

屏蔽了手机 身份证 在Discord 会显示出
![javaw_YWcANr08Oo](https://github.com/TrPlugins/TrChat/assets/25352223/8d5d67fe-01de-44bd-add3-71f1686df132)
![Discord_cS6pAhPOoN](https://github.com/TrPlugins/TrChat/assets/25352223/4ca1a7a4-102f-4751-81c7-3683c78f03ce)

### 配置文件

```YAML
General:
  Command-Controller:
    Enabled: false
    List:
      - 'arasple{exact: true}{condition: perm *trchat.admin}'
      - 'ver(sion)?(s)?{condition: perm *trchat.admin}'
      - 'help(s)?{condition: perm *trchat.admin}'
      - 'shout{cooldown: 3}'
  Mention:
    Enabled: false
    Self-Mention: false
    Permission: 'none'
    Cooldown: '30s'
    Notify: false
    Actions: [ ]
  Mention-All:
    Enabled: false
    Permission: 'trchat.function.mentionall'
    Cooldown: '5m'
    Notify: false
    Keys:
      - "@all"
      - "@everyone"
      - "@everybody"
      - "@所有人"
      - "@全體成員"
    Actions: [ ]
  Item-Show:
    Enabled: false
    Permission: 'none'
    Cooldown: '30s'
    Origin-Name: false
    Compatible: false
    Type: TRANSLATABLE
    Keys:
      - "%i%"
      - "%i"
      - "%item%"
      - "%item"
      - "[i]"
      - "[item]"
    Actions: [ ]
  Inventory-Show:
    Enabled: false
    Permission: 'trchat.function.inventoryshow'
    Cooldown: '30s'
    Keys:
      - '[inv]'
      - '[inventory]'
    Actions: [ ]
  EnderChest-Show:
    Enabled: false
    Permission: 'trchat.function.enderchestshow'
    Cooldown: '30s'
    Keys:
      - '[ender]'
      - '[enderchest]'
    Actions: [ ]
  Image-Show:
    Enabled: true
    Permission: 'trchat.function.imageshow'
    Cooldown: '1m'
    Key: '!\[([^;]*)\]\(([a-zA-Z]+://[^\s]*)\)'
    Actions: [ ]
  Custom:
    CustomFuCommand:
      condition: ~
      priority: 100
      pattern: 'fu'
      run-commands:
        - 'say hello'
  
Custom:
  # 示例 —— 網站分享
  shareUrl:
    pattern: '((https|http|ftp|rtsp|mms)?:\/\/)[^\s]+'
    display:
      text: '&8[&f&l網頁&8]'
      hover:
        - ''
        - '&3網頁: {0}'
        - ''
        - '&7點擊進入!'
        - ''
        - '&8[&c!&8] &7謹防任何詐騙與病毒'
      url: '{0}'

  # 示例 —— QQ 分享
  shareQQ:
    condition: ~
    priority: 100
    # 匹配表達式
    # 示例模塊的表達式部分來自互聯網
    pattern: 'QQ( )?[1-9]([0-9]{5,11})'
    # 變量 {0} 是按下方表達式提取後的內容, 可以不配置此項
    text-filter: '[1-9]([0-9]{5,11})'
    # 自定義顯示 JSON 組件
    display:
      text: '&8[&3&lQQ&8]'
      hover:
        - ''
        - '&3QQ: &b{0}'
        - ''
        - '&7這是一個 QQ 賬號,'
        - '&7你可以點擊此項快速打開聊天'
        - ''
        - '&8[&c!&8] &7請勿進行任何金錢交易'
        - '&8[&c!&8] &7交友需謹慎'
      url: 'https://wpa.qq.com/msgrd?v=3&uin={0}&site=qq&menu=yes'

  # 示例 —— B站視頻 分享
  shareBilibili:
    pattern: 'BV( )?.{10}'
    text-filter: '.{12}'
    # 自定義顯示 JSON 組件
    display:
      text: '&8[&f&lBilibili&8]'
      hover:
        - ''
        - '&7這可能是一個 Bilibili 視頻,'
        - '&7點擊即可訪問'
        - ''
        - '&3BV號: &b{0}'
      url: 'https://www.bilibili.com/video/{0}'

  # 示例 —— 防止玩家暴露、分享真實手機號
  hidePhoneNumber:
    pattern: '((13[0-9])|(14[0-9])|(15[0-9])|(17[0-9])|(18[0-9]))\d{8}'
    display:
      text: '&8[&c&m-&8]'
      hover:
        - '&7該內容疑似為手機號碼,'
        - '&7已自動屏蔽隱藏.'
        - ''
        - '&8[&c!&8] &7請勿分享任何隱私信息'
       

  # 示例 —— 隱藏大陸身份證
  hideIDCardNumber:
    pattern: '([1-9]\d{5}[12]\d{3}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])\d{3}[0-9xX])'
    display:
      text: '&8[&c&m-&8]'
      hover:
        - '&7該內容疑似為身份證號,'
        - '&7已自動屏蔽隱藏.'
        - ''
        - '&8[&c!&8] &7請勿分享任何隱私信息'
        - '&7嚴重者可能處於禁言/封禁'




  # 示例 —— 高亮 IP
  glowIP:
    pattern: '(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)\.(25[0-5]|2[0-4]\d|[0-1]\d{2}|[1-9]?\d)'
    display:
      text: '&e&n{0}'
      hover:
        - '&7這是一個 IP地址'
        - '&7點擊複製!'
      copy: '{0}'

  # 示例 —— 高亮郵箱
  glowEmail:
    pattern: '\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}'
    display:
      text: '&e&n{0}'
      hover:
        - '&7這是一個郵箱'
        - '&7點擊複製!'
      copy: '{0}'
```

### 服务器环境

服务器版本:
1.20.1
插件列表:
[10:45:36 INFO]: Bukkit Plugins: (46):
[10:45:36 INFO]:  - AnnouncerPlus, Bank, BlockLocker, Citizens, CMI, *CMIEInjector, CMILib, Core, DecentHolograms, DiscordSRV
[10:45:36 INFO]:  Elevator, FastAsyncWorldEdit, Gifts, HeadDatabase, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, Invero, ItemsAdder, LoneLibs
[10:45:36 INFO]:  LotteryItem, LuckPerms, MMOCore, MMOItems, ModelEngine, *MoreBagPro, Multiverse-Core, MythicLib, MythicMobs, NBTAPI
[10:45:36 INFO]:  NoPlugins, PlaceholderAPI, PlayerGuild, PlayerPoints, PlayerTitle, PlayerWarp, ProtocolLib, QuickShop, RPGInventory, Shopkeepers
[10:45:36 INFO]:  spark, TAB, TrChat, Vault, WorldBorder, WorldGuard
