### ISSUE TITLE
[问题] 云端屏蔽问题

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#349]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

![Discord_4zQoxSRUAD](https://github.com/TrPlugins/TrChat/assets/25352223/c7a99b19-9d81-43c5-80a4-78a226522c32)
云端屏蔽无法屏蔽

![image](https://github.com/TrPlugins/TrChat/assets/25352223/1ceb8d92-e503-4693-9361-27e1096ae792)

版本是 TrChat-2.0.11

### 配置文件

```YAML
Enable:
  Chat: true
  Sign: true
  Anvil: true
  Item: false

Cloud-Thesaurus:
  Enabled: true
  Ignored: ['nt']
  Urls:
    - 'https://raw.githubusercontent.com/MOMOas/text-mute/main/mute.json '

Local:
  - 'NMSL'
  - 'fuck'
  - 'shit'

Ignored-Punctuations: ['!','.',',','#','$','%','&','*','(',')','|','?','/','@','"','\',';','[',']','{','}','+','~','-','_','=','^','<','>',' ','　','！','。','，','￥','（','）','？','、','“','‘','；','【','】','——','……','《','》','\\', '`']
WhiteList: ['has been']
Replacement: '*'
```

### 服务器环境

服务器版本:
1.20.1
插件列表:
[12:16:50 INFO]: Bukkit Plugins: (50):
[12:16:50 INFO]:  - AnnouncerPlus, Bank, BlockLocker, Citizens, CMI, *CMIEInjector, CMILib, Core, CosmeticsCore, Craftorithm
[12:16:50 INFO]:  DecentHolograms, DiscordSRV, Elevator, FastAsyncWorldEdit, Gifts, HeadDatabase, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, Invero
[12:16:50 INFO]:  ItemsAdder, LoneLibs, LotteryItem, LuckPerms, MMOCore, MMOItems, ModelEngine, *MoreBagPro, Multiverse-Core, MythicLib
[12:16:50 INFO]:  MythicMobs, NBTAPI, NoPlugins, PlaceholderAPI, PlayerGuild, PlayerPoints, PlayerTitle, PlayerWarp, ProtocolLib, QuickShop
[12:16:50 INFO]:  RPGInventory, SakuraBind, Shopkeepers, spark, Spectator, TAB, TrChat, Vault, WorldBorder, WorldGuard
