### ISSUE TITLE
[功能] 将私聊权限和私聊频道进入权限分离

### ISSUE THREAD

**Issue by Dreeam-qwq** [FlickerProjects/TrChat#353]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

RT, 将私聊频道进入权限 和 使用/msg等私聊指令进行私聊的权限分开，进入私聊频道一个权限，使用/msg id message等私聊指令私聊是另一个权限

希望的功能:

- 玩家可以使用/msg id message私聊指令进行私聊，但是不能使用/msg id直接进入私聊频道

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8030903080
直接说话条件写在Speak-Condition中
禁用Join-Permission权限

**Comment by Dreeam-qwq** [comment]
使用lp设置default组 `trchat.admin`权限false，`trchat.private` 权限true

![image](https://github.com/TrPlugins/TrChat/assets/61569423/87e28b05-c3a5-442b-a50c-ec8aad0044cb)

配置文件:
```
Options:
  Join-Permission: 'trchat.admin'
  Speak-Condition: 'perm *trchat.private'
  Proxy: false
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'tell']

Sender:
  - prefix:
      sender:
        text: '&8[&a%player_name% &7➦ %trchat_toplayer%&3&8] '
    msg:
      default-color: 'f'
      hover: ''

Receiver:
  - prefix:
      receiver:
        text: '&8[&6%player_name% &7➥ &2%trchat_toplayer%&8] '
    msg:
      default-color: 'f'
      hover: ''

```

服务端: Leaf 1.20.4

另外能不能问一下，[文档](https://trchat.trixey.cc/guide/channel/settings#%E9%80%89%E9%A1%B9)里的`需要权限才能可以加入频道(听到消息)` 听到消息是什么意思，只有Speak-Condition权限没有Join-Permission权限，没用/msg加入私聊频道的情况下，还可以正常发送接收私聊吗(
