### ISSUE TITLE
[问题] 无法@人

### ISSUE THREAD

**Issue by explorer3039** [FlickerProjects/TrChat#354]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

尝试@一个玩家，无效
尝试@所有人，有效

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.0
  Cooldown: '0.5s'
  Length-Limit: 256

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 服务器环境

服务器版本:
This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
Error obtaining version information
Previous version: git-Purpur-1171 (MC: 1.16.5)
插件列表:
Plugins (35): ChestCommands, Chunky, Citizens, CleanroomGenerator, CMILib, DecentHolograms, Essentials, FallingSnow, InfiniteScoreboard, ItemEdit, ItemTag, LuckPerms, MiniMOTD, Multiverse-Core, PlaceholderAPI, PlayerKits2, PlugManX (PlugMan), ProMCCore, ProRPGItems (QuantumRPG), ProtocolLib, QuickShop, Residence, ShopGUIPlus, Shopkeepers, SkinsRestorer, spark, TAB, TerraformGenerator, TrChat, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEdit, WorldGuard
