### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Forizing** [FlickerProjects/TrChat#356]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

玩家使用/tell命令提示需要玩家,添加玩家参数后显示未知参数
<img width="357" alt="image" src="https://github.com/TrPlugins/TrChat/assets/142212639/b1413acf-ba50-45bc-b024-0a450c14f61d">
<img width="471" alt="image" src="https://github.com/TrPlugins/TrChat/assets/142212639/830f4ad0-2823-45b4-8920-0f7192a7b1ff">
<img width="264" alt="image" src="https://github.com/TrPlugins/TrChat/assets/142212639/1d062f26-cc4c-4f23-9129-acc67f5ec3cc">

### configuration file

```YAML
Options:
  Join-Permission: 'trchat.private'
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'tell', 'm', "w"]

Sender:
  - prefix:
      sender:
        text: '&8[&a%player_name% &7➦ &6%trchat_toplayer%&3&8] '
    msg:
      default-color: 'f'
      hover: '&7在 %server_time_HH:mm:ss% 由 %player_name% 所发送'

Receiver:
  - prefix:
      receiver:
        text: '&8[&6%player_name% &7➥ &2%trchat_toplayer%&8] '
    msg:
      default-color: 'f'
      hover: '&7在 %server_time_HH:mm:ss% 由 %player_name% 所发送'
```

### logs

同正常使用/tell一样

### Server environment

Server version:
Minecraft Waterfall->Paper 1.18.2
Plugin list:
不给,Trchat2.0.11
