### ISSUE TITLE
[问题] 聊天间隔冷却对私聊不起作用

### ISSUE THREAD

**Issue by Dreeam-qwq** [FlickerProjects/TrChat#364]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 确保Normal频道中聊天冷却正常生效
2. 使用/msg或者其他私聊指令刷屏
3. 没有冷却间隔

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: NONE
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: false
  Sign: false
  Anvil: false
  Book: false
```

### 服务器环境

服务器版本: 1.20.4
插件列表:
...
