### ISSUE TITLE
[help] or [Feature] private console condition

### ISSUE THREAD

**Issue by Zarkness2** [FlickerProjects/TrChat#367]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

I want to put a condition to the messages that the console sends in the private.yml, since I want to put that the user can choose the aesthetic format that he likes more since I change it for messages between users also I would like to do it for when the console sends him a msg.

but in spite of not having the permission trchat.private.haruto.console.1 it does not send me the message that it should if you do not have that permission.

```yml
Options:
  Join-Permission: 'trchat.private'
  Proxy: false
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Sender:
  - prefix:
      sender:
        - condition: 'perm *trchat.private.haruto.speak'
          text: '&8[&a%player_name% &7➦ %trchat_toplayer%&3&8] '
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to contact with op
            &f
          suggest: '/tell %player_name% '
        - text: '&8[&a%player_name% &7➦aa %trchat_toplayer%&3&8] '
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to chat with me
            &f
          suggest: '/tell %player_name% '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&8[&6%player_name% &7➥ &2%trchat_toplayer%&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        - condition: 'perm *trchat.private.haruto.console.1'
          text: '&8[<g:#97e8fc:#fbea9f>Haruto &7➥ &2you&8] '
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to contact with op
            &f
        - text: '&8[<g:#97e8fc:#fbea9f>Haruto &7➥aasd &2you&8] '
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to chat with me
            &f
    msg:
      default-color: 'f'
 ```
