### ISSUE TITLE
[问题] 2.1.0版本rgb 字体问题

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#376]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

        text: '&{#a1a8b3}🗣 &8[&e全頻&8] &r%luckperms_prefix% &7|&r'   这段用rgb字体会后台出错

### 配置文件

```YAML
Options:
  # 聊天可视范围
  Target: ALL
  Auto-Join: true
  # 有敏感词就会禁止发送
  Filter-Before-Sending: false
  # 是否传输消息到DiscordSRV
  Send-To-Discord: true
  # 是否接受DiscordSRV的消息
  Receive-From-Discord: true 
  Discord-Channel: "全頻"

Bindings:
  Command: ['玩家頻道', 'default', 'global', '全頻']
  
Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&r'
      hover: '&7現在時間: %server_time_ah:mm:ss %'
    prefix:
      world:
        text: '&{#a1a8b3}🗣 &8[&e全頻&8] &r%luckperms_prefix% &7|&r'
        hover: |-
          &r
          &8▪ &7位置: &3%player_world%
          &r
          &6▶ &e點擊這裡發送傳送請求
          &r
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&e%player_name%'
          hover: |-
            &r
            &8▪ &7世界: &7%player_world%
            &8▪ &7金錢: &b%vault_eco_balance_fixed% 元
            &8▪ &7點數: &b%playerpoints_points% &3點             
            &8▪ &7等級: &r%mmocore_level%          
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &8▪ &7延遲: &3%player_ping% 毫秒
            &8▪ &7稱號: &r%playerTitle_use%
            &8▪ &7公會: &r%playerGuild_name%
            &r
            &6▶ &e點擊聯繫管理員
            &r
          suggest: '/msg %player_name% '
        - text: '&e%player_name%'
          hover: |-
            &r
            &8▪ &7世界: &7%player_world%
            &8▪ &7金錢: &b%vault_eco_balance_fixed% 元
            &8▪ &7點數: &b%playerpoints_points% &3點 
            &8▪ &7等級: &r%mmocore_level%         
            &8▪ &7生命值: &c%player_health_rounded% ❤
            &8▪ &7延遲: &3%player_ping% 毫秒
            &8▪ &7稱號: &r%playerTitle_use%
            &8▪ &7公會: &r%playerGuild_name%
            &r
            &6▶ &e點擊與我聊天
            &r
          suggest: '/msg %player_name% '
      part-before-msg:
        text: ' &r» '
    suffix:
      example:
        text: ''
```

### 日志

[21:47:51 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.1.0
java.lang.IllegalArgumentException: Could not parse ChatColor {#a1a8b3}
        at net.md_5.bungee.api.ChatColor.of(ChatColor.java:273) ~[bungeecord-chat-1.20-R0.1-deprecated+build.14.jar:?]
        at me.arasple.mc.trchat.util.color.HexUtils.translateHex(HexUtils.java:267) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.util.color.HexUtils.parseHex(HexUtils.java:217) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.util.color.HexUtils.colorify(HexUtils.java:68) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.util.color.HexKt.colorify(Hex.kt:13) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.module.display.format.obj.Text.process(Text.kt:31) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:21) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:148) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[TrChat-2.1.0.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[TrChat-2.1.0.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2385) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor205.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:200) ~[InteractiveChat-4.2.9.0.jar:?]
        at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.9.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 服务器环境

服务器版本:
1.20.2
插件列表:
[21:49:18 INFO]: Bukkit Plugins: (58):
[21:49:18 INFO]:  - AnnouncerPlus, Bank, BlockLocker, ChestPreview, Citizens, CMI, *CMIEInjector, CMILib, Core, CoreProtect
[21:49:18 INFO]:  CosmeticsCore, DecentHolograms, DiscordSRV, DungeonPlus, Elevator, EpicCraftingsPlus, FastAsyncWorldEdit, Gifts, HeadDatabase, InteractionVisualizer
[21:49:18 INFO]:  InteractiveChat, InteractiveChatDiscordSrvAddon, Invero, ItemsAdder, LoneLibs, LotteryItem, LuckPerms, MMOCore, MMOItems, ModelEngine
[21:49:18 INFO]:  MoreBagPro, Multiverse-Core, MythicCrucible, MythicLib, MythicMobs, NBTAPI, NoPlugins, PlaceholderAPI, PlayerGuild, PlayerPoints
[21:49:18 INFO]:  PlayerTitle, PlayerWarp, PlayerWarp, ProtocolLib, QuickShop, RPGInventory, SakuraBind, Shopkeepers, spark, Spectator
[21:49:18 INFO]:  TAB, TimedItem, TrChat, TreasureChestX, Vault, WorldBorder, WorldGuard, YuIllustration
