### ISSUE TITLE
[问题] [12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: No SLF4J providers were found 日志无法输出

### ISSUE THREAD

**Issue by 2689508458** [FlickerProjects/TrChat#380]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: No SLF4J providers were found.
[12:47:38 WARN]: Nag author(s): '[Arasple, ItsFlicker]' of 'TrChat v2.1.0' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
已开启mysql

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: mysql
  SQL:
    host: localhost
    port: 3306
    user: root
    password: xy6666
    database: trchat
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[12:47:38 INFO]: [TrChat] Enabling TrChat v2.1.0
[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: No SLF4J providers were found.
[12:47:38 WARN]: Nag author(s): '[Arasple, ItsFlicker]' of 'TrChat v2.1.0' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[12:47:38 ERROR]: [TrChat] [STDERR] SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[12:47:38 INFO]: [PlaceholderAPI] Successfully registered internal expansion: trchat [2.1.0]
[12:47:38 INFO]: [TrChat] 当前无跨服支持.
[12:47:38 INFO]: [TrChat] 聊天 | 成功载入 13 个聊天功能... [7 Ms]
[12:47:38 INFO]: [TrChat] 过滤器 | 已载入本地敏感词库总计 3 个.
[12:47:38 INFO]: [TrChat] 聊天 | 成功载入 4 个聊天频道... [11 Ms]
[12:47:38 INFO]: [TrChat] 信息 | 加载完毕. TrChat v2.1.0 现已启用, 敬请使用.

### 服务器环境

服务器版本:
leaves-1.20.4.jar
插件列表:
[12:52:48 INFO]: Server Plugins (29):
[12:52:48 INFO]: Bukkit Plugins:
[12:52:48 INFO]:  - AuthMe, BlueMap, ChestCommands, ClearEntity, EzChestShop, GSit, LevelledMobs, LiteSignIn, *LockettePro, *Lores
[12:52:48 INFO]:  LuckPerms, Multiverse-Core, *MultiverseCoreBug, NBTAPI, NekoMaid, PlaceholderAPI, Plan, PlayerPoints, PlugManX, *ProtectionLib
[12:52:48 INFO]:  *SeekInventory, TAB, TrChat, Uniporter, Vault, ViaBackwards, ViaVersion, WorldEdit, YukiNoaAPI
