### ISSUE TITLE
[问题] “服务器名称”变量显示异常。无论什么都显示now available in...什么什么的

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [FlickerProjects/TrChat#384]
<img width="511" alt="image" src="https://github.com/TrPlugins/TrChat/assets/141799770/360e842a-ef5f-4da1-9e6c-d5859a88a339">

### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

随便加个显示所处服务器的变量就行，比如%server%或者%player_server%

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Disabled-Commands: []

Channel:
  Default: 'Global'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
#BC中转站与所有联通的服务器的这个配置文档都是一样的
```

### 日志

没有错误

### 服务器环境

服务器版本:
...一号服务端：[18:19:30 INFO]: This server is running Mohist version 1.20.1-629 (MC: 1.20.1) (
Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge v
ersion 47.1.79)
二号服务端：[18:20:15 INFO]: This server is running Paper version git
 (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 92
You are running the latest version
Previous version: git-Paper-298 (MC: 1.20.2)
插件列表:
...一号服务端：[18:22:11 INFO]: Plugins (44): CoreProtect, RaiseUp, PlaceholderAPI, CMILib, Hol
ographicDisplays, Seasons, ConsoleSpamFix, LaggRemover, NoSpawnChunks, LiteSignI
n, LiteCustomAnnouncer, TrChat, HIM, ChineseNickName, GameModeTimerPlugin, BanIt
em, Shift_Menu, LuckPerms, AnimatedScoreboard, TabTPS, LoneLibs, ProtocolLib, Sk
insRestorer, GSit, Vault, dynmap, Essentials, ItemCommands, ServerBooster, VeinM
iner, Multiverse-Core, ChestCommands, Residence, EssentialsChat, Interface4, Cus
tomSprays, MTVehicles, AuthMe, WorldBorder, QuickShop, Space, PlugManX (PlugMan)
, Mohist, ViaVersion
>

二号服务端：[18:22:40 INFO]:  - AnimatedScoreboard, AuthMe, ChestCommands, *ChineseNic
 Citizens, CMILib, *CommandNPC, ConsoleSpamFix, CoreProtect, dynmap
[18:22:40 INFO]:  SkinsRestorer, TabTPS, TrChat, Vault, ViaBackwards, ViaV
, WorldEdit

当变量为%server_name%的时候，会显示为默认Motd，并不能显示我们的真正Motd
![Screenshot_2024-04-10-11-34-25-099_com tungsten fcl-edit](https://github.com/TrPlugins/TrChat/assets/141799770/38004acc-2af1-4619-9775-cfa98c1571c3)
