### ISSUE TITLE
[问题] Normal的Auto-Join不生效

### ISSUE THREAD

**Issue by HansOffice** [FlickerProjects/TrChat#390]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

![image](https://github.com/TrPlugins/TrChat/assets/94523696/033246ee-7819-495f-a5de-06600277dbad)
当玩家离开全服聊天频道后不会自动进入normal频道
我将我的聊天频道全部移除后让插件重新生成的聊天频道文件依旧会出现这样的问题
群组插件版本也为最新版，依旧没有任何效果
normal频道的自动加入功能并不生效，导致玩家离开全服聊天频道后无法再发送消息
该问题没有发生在我之前使用的2.0.4版本

### 配置文件

```YAML
Options:
  Target: ALL
  Auto-Join: true

Bindings:
  Prefix: ['!normal']
  Command: ['mal', 'normal']

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&7'
      hover: '&7Date: %server_time_HH:mm:ss%'
    prefix:
      world:
        text: '&8[&3%player_world%&8]'
        hover: |-
          &f
          &8▪ &7Location: &3%player_world%&7, &2%player_x%/%player_y%/%player_z%
          &f
          &6▶ &eClick here to send a teleport request
          &f
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&4%player_name%'
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to contact with op
            &f
          suggest: '/tell %player_name% '
        - text: '&7%player_name%'
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to chat with me
            &f
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&7: '
    suffix:
      example:
        text: ''





Options:
  Speak-Condition: 'perm "trchat.global"'
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Bindings:
  Prefix: ['!all']
  Command: ['global', 'all', 'shout']

Formats:
  - condition: null
    prefix:
      server:
        text: '&8[&3%server_name%&8] '
        hover: |-
          &7Server &3%server_name%
          &f
          &7Version: &6%server_version%
          &7Online: &a%server_online%&7/&2%server_max_players%
          &7TPS: &b%server_tps%
      player:
        text: '&e%player_name%&8: '
    msg:
      default-color: 'f'
      hover: '&7Date: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&eServer&8: '
    msg:
      default-color: 'l'
```

### 日志

[latest.log](https://github.com/TrPlugins/TrChat/files/15052991/latest.log)

### 服务器环境

服务器版本: purpur1.20,2
...
插件版本: 2.1.0
...
