### ISSUE TITLE
[Feature] 可以禁言未在线的玩家，禁言时不允许使用/tm指令

### ISSUE THREAD

**Issue by WarmRhombus** [FlickerProjects/TrChat#393]
### Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### Detailed description

```
1. 玩家不在线时，禁言没有任何反应，请求可以正常禁言未在线玩家
2. 玩家被禁言时，可以使用原版指令发送消息，比如/tm，请求加个禁言时可以禁用某些指令
```

**Comment by Clexus** [comment]
速度加入禁言离线玩家，这个功能不知道为什么一直没有，要禁言玩家他跑了那我怎么处理@ItsFlicker

**Comment by ItsFlicker** [comment]
2.3.7已支持
禁用命令可以这样实现
```yaml  
  Command-Controller:
    Enabled: true
    List:
      - 'tm{condition: mute check}'
```
