### ISSUE TITLE
[问题] functions中的匹配内容替换优先级应大于变量

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#398]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

```
  test:
    condition: ~
    pattern: '.*'
    display:
      text: '%revstr_{0}%'
```
revstr用来输出颠倒的字符串
输入：123
理论输出：321
实际输出: }0{

### 配置文件

```YAML
无
```

### 服务器环境

无关
