### ISSUE TITLE
[功能] 让msg部分也能使用条件

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#404]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

例如这样
```yaml
    msg:
      - condition: 'check papi *%player_is_op% == *yes'
        default-color: '&4'
      - condition: 'check papi *%player_is_op% == *no'
        default-color: '&f'
        hover:
          - '&7发言时间 %server_time_YYYY/MM/dd HH:mm:ss%'
          - '&c[点击复制]'
        suggest: '%trchat_lastmessage_uncolored%'
```
