### ISSUE TITLE
[问题] VC跨服中部分消息发送后会被卡没

### ISSUE THREAD

**Issue by HiTech0926** [FlickerProjects/TrChat#411]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

群组端是Velocity，下面分了Lobby、A、B三个子服
在三个子服任意一个发送消息，都会直接卡没消息（基本上是每成功发送几条后，卡掉一次或几次消息），卡掉的消息VC后台也无显示

### 配置文件

```YAML
#所有子服的settings.yml均相同
Options:
  # 是否检查更新并提醒
  Check-Update: true
  # 强制使用跨服类型, 识别错误时可更改(AUTO, NONE, BUNGEE, VELOCITY)
  Proxy: AUTO
  # 记录普通聊天格式到plugins/TrChat/logs目录下的格式
  Log-Normal: '[{0}] {1}: {2}'
  # 记录私聊聊天格式到plugins/TrChat/logs目录下的格式
  Log-Private: '[{0}] {1} -> {2}: {3}'
  # 自动删除多少天前的聊天记录
  Log-Delete-Time: 0
  # 强制变量扩展
  Depend-Expansions: ['player', 'server']
  # 是否禁止玩家使用tab补全命令
  Prevent-Tab-Complete: false
  # 聊天发包最大长度限制
  Component-Max-Length: 327660
  # 是否允许Kether宽容解析
  Kether-Allow-Tolerance-Parser: true
  # 欺骗客户端已开启安全聊天 (阻止右上角弹窗)
  Cheat-Client-Secure-Chat: true
  # 是否启用发包/处理包
  Use-Packets: true
  # 禁用的命令
  Disabled-Commands: []
  

# 默认频道
Channel:
  Default: 'Normal' # 改为Global即可全局跨服聊天

# 数据库
Database:
  # 数据库类型 (SQLite,SQL)
  Method: SQLite
  SQL:
    # 数据库地址
    host: localhost
    # 数据库端口
    port: 3306
    # 数据库用户名
    user: trchat
    # 数据库密码
    password: 123456
    # 数据库名
    database: trchat
    # 数据库表名
    table: trchat_user_data

# Redis相关配置
Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

# 聊天功能
Chat:
  # 内容相似度防刷屏 (设为0禁用)
  Anti-Repeat: 0.5
  # 聊天间隔冷却
  Cooldown: '1s'
  # 最大聊天长度
  Length-Limit: 200

# 颜色转换
Color:
  # 聊天颜色
  Chat: true
  # 告示牌颜色
  Sign: true
  # 铁砧颜色
  Anvil: true
  # 书本颜色
  Book: true

# 是否启用行内复合文本
Simple-Component:
  # 悬浮文字
  Hover: true
  # 铁砧
  Anvil: true
  # 告示牌
  Sign: true




#除Lobby外，两个子服的频道文件Normal.yml，但是跨服（里面Ports为三个子服的端口）

Options:
  Target: ALL
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true
  Ports: 5010;5011;5012

Events:
  Process: |-
    filter get &message

Formats:
  - condition: ~
    prefix:
      location:
        text: '&7[&#fcfc89&l粘&#f9f9a4&l液&#f6f6bf&l生&#f3f3da&l存&7]&r'
        hover: |-
          &#adf3fd=&#aff3fb=&#b0f3f9=&#b2f4f8=&#b4f4f6=&#b6f4f4=&#b7f4f2=&#b9f4f1=&#bbf5ef=&#bcf5ed=&#bef5eb=&#c0f5ea=&#c2f5e8=&#c3f6e6=&#c5f6e4=&#c7f6e2=&#c8f6e1=&#caf6df=&#ccf7dd=&#cef7db=&#cff7da=&#d1f7d8=&#d3f8d6=&#d5f8d4=&#d6f8d3=&#d8f8d1=&#daf8cf=&#dbf9cd=&#ddf9cb=&#dff9ca=&#e1f9c8=&#e2f9c6=&#e4fac4=&#e6fac3=&#e7fac1=&#e9fabf=&#ebfabd=&#edfbbc=&#eefbba=&#f0fbb8=
          &f
          &#fcfc89所&#f9f9a4在&#f6f6bf位&#f3f3da置&f: 
          &7[&#fcfc89&l粘&#f9f9a4&l液&#f6f6bf&l生&#f3f3da&l存&7] - &7[&b&l%server_name%&7] - &7[&r%multiverse_world_alias%&7]&f: &2%player_x% %player_y% %player_z%
          &f
          &#fcfc89区&#f9f9a4服&#f6f6bf在&#f3f3da线&f: &a%server_online%
          &#fcfc89区&#fafa9d服&#f8f8b2T&#f5f5c6P&#f3f3daS&f: &a%server_tps%
          &f
          &#adf3fd&l点&#b4f4f6&l击&#baf5ef&l即&#c1f5e8&l可&#c8f6e1&l发&#cff7db&l送&#d5f8d4&l传&#dcf9cd&l送&#e3f9c6&l请&#e9fabf&l求&#f0fbb8&l~
          &f
          &#adf3fd=&#aff3fb=&#b0f3f9=&#b2f4f8=&#b4f4f6=&#b6f4f4=&#b7f4f2=&#b9f4f1=&#bbf5ef=&#bcf5ed=&#bef5eb=&#c0f5ea=&#c2f5e8=&#c3f6e6=&#c5f6e4=&#c7f6e2=&#c8f6e1=&#caf6df=&#ccf7dd=&#cef7db=&#cff7da=&#d1f7d8=&#d3f8d6=&#d5f8d4=&#d6f8d3=&#d8f8d1=&#daf8cf=&#dbf9cd=&#ddf9cb=&#dff9ca=&#e1f9c8=&#e2f9c6=&#e4fac4=&#e6fac3=&#e7fac1=&#e9fabf=&#ebfabd=&#edfbbc=&#eefbba=&#f0fbb8=
        command: '/tpa %player_name%'
      part-before-title:
        text: ' '
      title:
        - text: '&r%playerTitle_use%&r'
          hover: |-
            &f
            &#fcfc89玩&#f9f9a4家&#f6f6bf称&#f3f3da号&f: &r%playerTitle_use%
            &f
      part-before-player:
        text: ' '
      player:
        - text: '&e%player_name%&r'
          hover: |-
            &f
            &#fcfc89玩&#f9f9a4家&#f6f6bf延&#f3f3da迟&f: &a%player_ping% ms
            &#fcfc89玩&#f9f9a4家&#f6f6bf血&#f3f3da量&f: &c%player_health_rounded% ❤
            &f
            &#adf3fd&l点&#b7f4f3&l击&#c0f5e9&l即&#caf6df&l可&#d3f8d6&l发&#ddf9cc&l送&#e6fac2&l私&#f0fbb8&l聊
            &f
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&f: '
    msg:
      default-color: '&f'
      hover: '&#fcfc89发&#f9f9a4送&#f6f6bf日&#f3f3da期&f: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&7[&#fcfc89&l粘&#f9f9a4&l液&#f6f6bf&l生&#f3f3da&l存&7]&r'
    msg:
      default-color: '&l'





#Lobby子服的频道文件，是全局的
Options:
  Target: ALL
  Proxy: true
  Force-Proxy: true
  Double-Transfer: true
  Auto-Join: true

Events:
  Process: |-
    filter get &message

Formats:
  - condition: ~
    prefix:
      location:
        text: '&7[&#fcfc89&l登&#f9f9a4&l录&#f6f6bf&l大&#f3f3da&l厅&7]&r'
        hover: |-
          &#adf3fd=&#aff3fb=&#b0f3f9=&#b2f4f8=&#b4f4f6=&#b6f4f4=&#b7f4f2=&#b9f4f1=&#bbf5ef=&#bcf5ed=&#bef5eb=&#c0f5ea=&#c2f5e8=&#c3f6e6=&#c5f6e4=&#c7f6e2=&#c8f6e1=&#caf6df=&#ccf7dd=&#cef7db=&#cff7da=&#d1f7d8=&#d3f8d6=&#d5f8d4=&#d6f8d3=&#d8f8d1=&#daf8cf=&#dbf9cd=&#ddf9cb=&#dff9ca=&#e1f9c8=&#e2f9c6=&#e4fac4=&#e6fac3=&#e7fac1=&#e9fabf=&#ebfabd=&#edfbbc=&#eefbba=&#f0fbb8=
          &f
          &#fcfc89所&#f9f9a4在&#f6f6bf位&#f3f3da置&f: 
          &7[&#fcfc89&l登&#f9f9a4&l录&#f6f6bf&l大&#f3f3da&l厅&7]&f: &2%player_x% %player_y% %player_z%
          &f
          &#fcfc89区&#f9f9a4服&#f6f6bf在&#f3f3da线&f: &a%server_online%
          &#fcfc89区&#fafa9d服&#f8f8b2T&#f5f5c6P&#f3f3daS&f: &a%server_tps%
          &f
          &#adf3fd=&#aff3fb=&#b0f3f9=&#b2f4f8=&#b4f4f6=&#b6f4f4=&#b7f4f2=&#b9f4f1=&#bbf5ef=&#bcf5ed=&#bef5eb=&#c0f5ea=&#c2f5e8=&#c3f6e6=&#c5f6e4=&#c7f6e2=&#c8f6e1=&#caf6df=&#ccf7dd=&#cef7db=&#cff7da=&#d1f7d8=&#d3f8d6=&#d5f8d4=&#d6f8d3=&#d8f8d1=&#daf8cf=&#dbf9cd=&#ddf9cb=&#dff9ca=&#e1f9c8=&#e2f9c6=&#e4fac4=&#e6fac3=&#e7fac1=&#e9fabf=&#ebfabd=&#edfbbc=&#eefbba=&#f0fbb8=
      part-before-title:
        text: ' '
      title:
        - text: '&r%playerTitle_use%&r'
          hover: |-
            &f
            &#fcfc89玩&#f9f9a4家&#f6f6bf称&#f3f3da号&f: &r%playerTitle_use%
            &f
      part-before-player:
        text: ' '
      player:
        - text: '&e%player_name%&r'
          hover: |-
            &f
            &#fcfc89玩&#f9f9a4家&#f6f6bf延&#f3f3da迟&f: &a%player_ping% ms
            &#fcfc89玩&#f9f9a4家&#f6f6bf血&#f3f3da量&f: &c%player_health_rounded% ❤
            &f
            &#adf3fd&l点&#b7f4f3&l击&#c0f5e9&l即&#caf6df&l可&#d3f8d6&l发&#ddf9cc&l送&#e6fac2&l私&#f0fbb8&l聊
            &f
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&f: '
    msg:
      default-color: '&f'
      hover: '&#fcfc89发&#f9f9a4送&#f6f6bf日&#f3f3da期&f: %server_time_HH:mm:ss%'

# Can't use placeholders!
Console:
  - prefix:
      server:
        text: '&7[&#fcfc89&l登&#f9f9a4&l录&#f6f6bf&l大&#f3f3da&l厅&7]&r'
    msg:
      default-color: '&l'


```

### 日志
无

### 服务器环境

服务器版本:
[00:12:58 INFO]: Current: git-Purpur-2166 (MC: 1.20.4)*
* You are 10 version(s) behind
Download the new version at: https://purpurmc.org/downloads

插件列表:
（即使只有TrChat和PlaceholderAPI也会出现该问题）

[00:13:13 INFO]: Bukkit Plugins: (25):
[00:13:13 INFO]:  - AuthMe, Citizens, CoreProtect, DecentHolograms, DeluxeHub, FastAsyncWorldEdit, GSit, Images, *LoginManager, LoneLibs
[00:13:13 INFO]:  LuckPerms, Multiverse-Core, NBTAPI, PlaceholderAPI, Plan, PlugManX, ProtocolLib, SimpleWhitelist, spark, TAB-Bridge
[00:13:13 INFO]:  TrChat, TrMenu, ViaBackwards, ViaVersion, WorldGuard
