### ISSUE TITLE
[功能] 让Functions里的自定义功能也支持权限、冷却等等

### ISSUE THREAD

**Issue by Clexus** [FlickerProjects/TrChat#416]
### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 详细的描述

类似于:
```
 我的信息:
    pattern: '(?<=^)(我的信息)(?=$)'
    permission: 'op'
    cooldown: '5s'
    cooldown-message: "冷却中，请等待%s"
    display:
      text: '&r&l[&b&l我的信息&r&l]'
      hover:
      - 'xxxxxx'
```

**Comment by ItsFlicker** [comment]
```yaml 
我的信息:
    pattern: '(?<=^)(我的信息)(?=$)'
    condition: 'perm "xxx"'
    cooldown: '5s'
    cooldown-message: "冷却中，请等待{0}秒"
    display:
      text: '&r&l[&b&l我的信息&r&l]'
      hover:
      - 'xxxxxx'
```
