### ISSUE TITLE
[问题] VS跨服私聊有时找不到私聊玩家

### ISSUE THREAD

**Issue by HYDeath** [FlickerProjects/TrChat#419]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

以下均玩家都在线，均以velocity通讯了,TAB补充/手动输入玩家名字均都找不到
1.单子服有时候私聊无法找到玩家，有时能找得到有时找不到。
2.任意子服跨其他子服私聊也跟上方一样，有时候能出现有时候不能出现

### 配置文件

```YAML
频道配置：
> 
Options:
  Join-Permission: 'trchat.private'
  Proxy: true
  Disabled-Functions: ['Mention']
  Private: true

Bindings:
  Command: ['msg', 'message', 'tell', 'talk', 'm', 'whisper', 'w']

Sender:
  - prefix:
      sender:
        text: '&8[&e☬&8] &8[&b我 &7➦ %trchat_toplayer%&3&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

Receiver:
  - prefix:
      receiver:
        text: '&8[&a☬&8] &8[&6%player_name% &7➥ &b我&8] '
    msg:
      default-color: 'f'
      hover: '&7日期: %server_time_HH:mm:ss%'

setinggs文件：
> ```yaml
Options:
  # 是否检查更新并提醒
  Check-Update: true
  # 强制使用跨服类型, 识别错误时可更改(AUTO, NONE, BUNGEE, VELOCITY)
  Proxy: AUTO
  # 记录普通聊天格式到plugins/TrChat/logs目录下的格式
  Log-Normal: '[{0}] {1}: {2}'
  # 记录私聊聊天格式到plugins/TrChat/logs目录下的格式
  Log-Private: '[{0}] {1} -> {2}: {3}'
  # 自动删除多少天前的聊天记录
  Log-Delete-Time: 0
  # 强制变量扩展
  Depend-Expansions: ['player', 'server']
  # 是否禁止玩家使用tab补全命令
  Prevent-Tab-Complete: false
  # 聊天发包最大长度限制
  Component-Max-Length: 32766
  # 是否允许Kether宽容解析
  Kether-Allow-Tolerance-Parser: true
  # 欺骗客户端已开启安全聊天 (阻止右上角弹窗)
  Cheat-Client-Secure-Chat: true
  # 是否启用发包/处理包
  Use-Packets: true
  # 禁用的命令
  Disabled-Commands: []
  

# 默认频道
Channel:
  Default: 'Normal' # 改为Global即可全局跨服聊天

# 数据库
Database:
  # 数据库类型 (SQLite,SQL)
  Method: SQLite
  SQL:
    # 数据库地址
    host: localhost
    # 数据库端口
    port: 3306
    # 数据库用户名
    user: root
    # 数据库密码
    password: root
    # 数据库名
    database: trchat
    # 数据库表名
    table: trchat_user_data

# Redis相关配置
Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

# 聊天功能
Chat:
  # 内容相似度防刷屏 (设为0禁用)
  Anti-Repeat: 0.75
  # 聊天间隔冷却
  Cooldown: '2s'
  # 最大聊天长度
  Length-Limit: 100

# 颜色转换
Color:
  # 聊天颜色
  Chat: true
  # 告示牌颜色
  Sign: true
  # 铁砧颜色
  Anvil: true
  # 书本颜色
  Book: true

# 是否启用行内复合文本
Simple-Component:
  # 悬浮文字
  Hover: false
  # 铁砧
  Anvil: false
  # 告示牌
  Sign: false
```
```


### 日志

_No response_

### 服务器环境

服务器版本:
[23:15:52 INFO]: This server is running Luminol version git-Luminol-"d753f16" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d753f16 on ver/1.20.4)
Unknown version
Previous version: git-Luminol-"c06f539" (MC: 1.20.4)
插件列表:
...
[23:15:34 INFO]:  - BlockLocker, ChestProtect, CMILib, CoreProtect, Essentials, FreedomChat, GlobalMarketPlus, GSit, HeadDrop, ImageFrame
[23:15:34 INFO]:  LiteSignIn, LuckPerms, MiniMOTD, PlaceholderAPI, PlayerGuild, PlayerMenu, PlayerPoints, PlayerTitle, PlugManX, ProtocolLib
[23:15:34 INFO]:  Residence, TAB, TrChat, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit
