### ISSUE TITLE
[问题] 与 PlayerDoll 假人插件冲突

### ISSUE THREAD

**Issue by SnivyJ** [FlickerProjects/TrChat#421]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

安装PlayerDoll插件 召唤一个假人 聊天就出现@了
![MPL@Y _HI%%C%UXT~P18M8L](https://github.com/user-attachments/assets/65951857-b005-458d-965b-df891b11c846)

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Kether-Allow-Tolerance-Parser: true
  ChatEvent-Hooks: ['PlayMoreSounds', 'ChatBubbles', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

[18:39:22] [Server thread/INFO]: [PlayerDoll] Plugin Start Handshake
[18:39:22] [Server thread/INFO]: [PlayerDoll] Plugin Start Handshake
[18:39:22] [Server thread/INFO]: [PlayerDoll] Plugin Start Handshake
[18:39:22] [Server thread/INFO]: [PlayerDoll] Start capture Login Listener
[18:39:22] [Server thread/INFO]: [PlayerDoll] Notify Wait Thread
[18:39:22] [Server thread/INFO]: [PlayerDoll] Plugin set last Join Server
[18:39:22] [User Authenticator #5/INFO]: UUID of player jiao005 is d47a43c3-98cf-4375-929a-005f362d0412
[18:39:22] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:627) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:207) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.network.LoginListener.d(LoginListener.java:102) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:436) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:181) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1487) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4263-Spigot-491f367-bed1e3f]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.base/java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:547) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:57) ~[?:?]
        at java.base/java.lang.reflect.Field.get(Field.java:444) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyReflection$1.get(TinyReflection.java:153) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.getChannel(TinyProtocol.java:391) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:167) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 14 more
[18:39:22] [Netty Server IO #1/INFO]: [PlayerDoll] Doll Joined Successfully, Suspend Server-side Packet Sending.
[18:39:22] [Server thread/INFO]: [+] -jiao005
[18:39:22] [Server thread/INFO]: -jiao005[/127.0.0.1:58548] logged in with entity id 4545 at ([world]453.66839507519563, 78.5, -87.40158954839347)
[18:39:22] [Server thread/INFO]: [PlayerDoll] Capture Login Success
[18:39:22] [Server thread/INFO]: <-jiao005> hi im a bot

### 服务器环境

服务器版本:
This server is running CraftBukkit version 4263-Spigot-491f367-bed1e3f (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
插件列表:
Plugins (32): PlaceholderAPI, ProtectFarmLand, LagFixer, CustomPlaceholder, PlayerDoll, KcBot, Dongmuleather, TrChat, ViaVersion, ProtectItemFrame, TreeFeller, eBackup, ViaBackwards, LuckPerms, WTF, SbPlaceholder, ProtocolLib, GSit, Vault, dynmap, DecentHolograms, EpicRename, XConomy, PlayerPoints, Multiverse-Core, KeepInventory, DeluxeHub, Essentials, EssentialsProtect, HuskHomes, BungeeTabListPlus, PlugManX (PlugMan)
