### ISSUE TITLE
[issue] 无法将事件 PlayerLoginEvent 传递给 TrMenu v3.3.3a

### ISSUE THREAD

**Issue by GuieUamc** [FlickerProjects/TrChat#429]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

玩家反复登录或死亡后就会弹出这个bug 的后台

### configuration file

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### logs

[12:02:38 ERROR]: Could not pass event PlayerLoginEvent to TrMenu v3.3.3a
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at me.arasple.mc.trmenu.taboolib.module.nms.TinyProtocol.injectChannelInternal(TinyProtocol.java:370) ~[[T][菜单]TrMenu-3.3.3a.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.TinyProtocol.injectPlayer(TinyProtocol.java:346) ~[[T][菜单]TrMenu-3.3.3a.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:168) ~[[T][菜单]TrMenu-3.3.3a.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:943) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.verifyLoginAndFinishConnectionSetup(ServerLoginPacketListenerImpl.java:197) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:88) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1732) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1519) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:02:38 ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.0
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.injectChannelInternal(TinyProtocol.java:370) ~[[T][聊天]TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.injectPlayer(TinyProtocol.java:346) ~[[T][聊天]TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:168) ~[[T][聊天]TrChat-2.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:943) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.verifyLoginAndFinishConnectionSetup(ServerLoginPacketListenerImpl.java:197) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:88) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1732) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1519) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server environment

Server version:
  leaves-1.20.4
Plugin list:
![QQ20240815-122417](https://github.com/user-attachments/assets/d2e8d793-75c6-4188-8403-b11004b3bd9f)
