### ISSUE TITLE
[问题] 最新版TrChat 好像没法在papi上注册变量

### ISSUE THREAD

**Issue by MineSunshineone** [FlickerProjects/TrChat#431]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1.在1.21.1上安装最新版插件
2.私聊

### 配置文件

```YAML
Options:
  Check-Update: false
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Use-Packets: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQL
  SQL:
    host: localhost
    port: 3306
    user: 
    password: 
    database: 
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0
  Cooldown: '0.0s'
  Length-Limit: 100

Color:
  Chat: false
  Sign: true
  Anvil: true
  Book: true

Simple-Component:
  Hover: false
  Anvil: false
  Sign: false
```

### 日志

![image](https://github.com/user-attachments/assets/450bbe8d-56c8-4542-b128-bd46b28499a5)

### 服务器环境

服务器版本:
...>
[22:55:50 INFO]: This server is running Luminol version 1.21.1-DEV-dev/1.21.1@76f1b9d (2024-08-15T01:41:45Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-DEV-9b3a981 (MC: 1.20.6)
插件列表:
...[22:56:47 INFO]: Paper Plugins:
[22:56:47 INFO]:  - MiraiMC
[22:56:47 INFO]: Bukkit Plugins:
[22:56:47 INFO]:  - AntiPopup, ArmorStandEditor, AxInventoryRestore, BetterGUI, ChestProtect, CommandWhitelist, CoreProtect, CreeperConfetti, DeathMessage, Essentials
[22:56:47 INFO]:  GSit, ICTTools, InvSeePlusPlus, Kaiivoid, KissKiss, LiteSignIn, LuckPerms, MinePay, MiniMOTD, NoFlightInEnd
[22:56:47 INFO]:  PlaceholderAPI, ProtocolLib, SkullPlugin, TAB, ToolStats, TrChat, UseTranslatedNames, ViaBackwards, ViaVersion, voicechat
[22:56:47 INFO]:  WDSoundControl, Whitelist4QQ, WorldEdit, ZAutoBroadcast, ZeroshiftFcmd
