### ISSUE TITLE
[问题] 和folia版的placeholder api一起使用会报错导致插件加载失败

### ISSUE THREAD

**Issue by Aruvelut-123** [FlickerProjects/TrChat#434]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1. 下载[Folia版PAPI](https://github.com/Folia-Inquisitors/PlaceholderAPI-Folia/releases)
2. 下载最新版trchat
3. 安装到1.21.1 folia服务器内
4. 报错

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Use-Packets: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Simple-Component:
  Hover: false
  Anvil: false
  Sign: false
```

### 日志

[19:45:16 WARN]: me.arasple.mc.trchat.taboolib.common.inject.ClassVisitException: class me.arasple.mc.trchat.taboolib.module.nms.MinecraftVersion#init: VisitorGroup
{priority=0, list=[AwakeFunction(lifeCycle=NONE), AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCy
cle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), me.arasple.mc.trchat.taboolib.module.kether.KetherLoader@1bd8d7e1, me.arasple.mc.trc
hat.taboolib.common.platform.command.SimpleCommandRegister@16e9c00c, me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@4b91b57d
]} (LOAD)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:146)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)
[19:45:16 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
[19:45:16 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[19:45:16 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[19:45:16 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[19:45:16 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[19:45:16 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[19:45:16 WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:552)
[19:45:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:292)
[19:45:16 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1281)
[19:45:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357)
[19:45:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:45:16 WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:211)
[19:45:16 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[19:45:16 WARN]:        at [跨服聊天]TrChat-2.1.3.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)
[19:45:16 WARN]:        ... 18 more

### 服务器环境

服务器版本:
1.21.1-folia@9203a7a
插件列表:
BetterBoard, CMI, CMILib, LightAntiCheat, Maintenance, MaintenanceAddon, PlaceholderAPI, PlayerTitle, Residence, SkinRestorer, TAB, TPA, TrChat, Vault, ViaAprilFools, ViaBackwards, ViaRewind, ViaVersion, WorldEdit
