### ISSUE TITLE
[问题] 最新版TrChat在1.8.8服务器上收到redis消息报错

### ISSUE THREAD

**Issue by Aruvelut-123** [FlickerProjects/TrChat#435]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1. 下载最新版TrChat
2. 下载paper 1.8.8
3. 安装插件并设置

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Use-Packets: true
  Disabled-Commands: []

Channel:
  Default: 'Global'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Simple-Component:
  Hover: false
  Anvil: false
  Sign: false
```

### 日志

[09:49:22 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonArray()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[09:49:22 WARN]:        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:65)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[09:49:22 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[09:49:22 WARN]:        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[09:49:22 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[09:49:22 WARN]:        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[09:49:22 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[09:49:22 WARN]:        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[09:49:22 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[09:49:22 WARN]:        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
[09:49:22 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[09:49:22 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[09:49:22 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:768)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:717)
[09:49:22 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:689)
[09:49:22 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:34)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.module.chat.Components.parseRaw(Components.kt:48)
[09:49:22 WARN]:        at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:88)
[09:49:22 WARN]:        at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$RedisSide.execute(BukkitProxyProcessor.kt:246)
[09:49:22 WARN]:        at me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:46)
[09:49:22 WARN]:        at me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[09:49:22 WARN]:        at redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[09:49:22 WARN]:        at redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[09:49:22 WARN]:        at redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[09:49:22 WARN]:        at me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[09:49:22 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:49:22 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:49:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:49:22 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:49:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)

### 服务器环境

服务器版本:
This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
插件列表:
Plugins (27): WorldEdit, PlaceholderAPI, WorldGuard, MaintenanceAddon, TrChat, AntiDisconnectSpam, ViaVersion, LightAntiCheat, ViaBack
wards, ViaRewind, LuckPerms, VelocityReport, DeluxeHub, ViaRewind-Legacy-Support, ViaAprilFools, ProtocolLib, SkinsRestorer, Maintenance, Vault, AuthMe
, RankGrantPlus, TAB-Bridge, Citizens, PlayerTitle, TAB, AuthMeVelocity, FastLogin
