### ISSUE TITLE
[issue] 2.1.3版本用默认的配置normal文件，鼠标在玩家名字和世界上不显示tip

### ISSUE THREAD

**Issue by orange1184258252** [FlickerProjects/TrChat#446]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

用默认的配置normal文件，鼠标在玩家名字和世界上不显示tip提示内容！

### configuration file

```YAML
Options:
  Target: ALL
  Always-Listen: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&7'
      hover: '&7Date: %server_time_HH:mm:ss%'
    prefix:
      world:
        text: '&8[&3%player_world%&8]'
        hover: |-
          &f
          &8▪ &7Location: &3%player_world%&7, &2%player_x%/%player_y%/%player_z%
          &f
          &6▶ &eClick here to send a teleport request
          &f
        command: '/tpa %player_name%'
      part-before-player:
        text: ' '
      player:
        - condition: 'player op'
          text: '&4%player_name%'
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to contact with op
            &f
          suggest: '/tell %player_name% '
        - text: '&7%player_name%'
          hover: |-
            &f
            &8▪ &7Ping: &3%player_ping% Ms
            &8▪ &7Health: &c%player_health_rounded% ❤
            &f
            &6▶ &eClick to chat with me
            &f
          suggest: '/tell %player_name% '
      part-before-msg:
        text: '&7: '
    suffix:
      example:
        text: ''
```

### Server environment

Server version:
1.12.2-spigot
...
Plugin list:
...
