### ISSUE TITLE
[问题] 把物品放入铁砧进行修改名字的操作后，后台出现报错

### ISSUE THREAD

**Issue by orange1184258252** [FlickerProjects/TrChat#447]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

把物品放入铁砧进行修改名字的操作后，后台出现报错
使用的是TrChat-2.1.0版本的插件

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[09:31:27 ERROR]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_411]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1015) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:368) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2460) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_411]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_411]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_411]

### 服务器环境

服务器版本:
...1.12.2-spigot
插件列表:
Plugins (149): FileListener, AttackSpeedRemover, AntiBoat, PlugMan, DreamDelayCmd, PlayerTpPlayer, LuckPerms, LiteItemShow, VoidGen, FyTrash, XinxinBotApi, EssentialsPowerExp, Sell, AnCDK, Fgive, ProtocolLib, AckmanLoader, MCCore, FantaLib1.12, ChineseCommand, ReNoPlayerCommand, JulyLibrary, XinxinAutoReview, Law, ZombieNoBurn, PlaceholderAPI, MinePay, WorldCommandBlock, Friends3_0, EClean, GuoItemLoreCommand, TrChat, WzAwakening, BlueBossChallenge, DreamAntiFly, WorldEdit, DecentHolograms, CrazyAuctionsPlus, bAnnouncer, EP-WorldNotInteract, ILoreEdit, ItemControl, Adyeshach, LegendMaid, PlugManX, Vault, DragonChatBubble, DogHook, Chemdah, XinxinCustomMessage, XinxinBindKit, GemsPAPI, AkariCDK, HolographicDisplays, PackPlaceholderAPI, PlayerPoints, GrScriptBlock, DreamBind, PuerkasMarriage, DreamPoints, CowMonthCard, BilibiliVideo, Vegas, CMILib, LiteSignIn, LiteInvitation, TAB, XinxinApi, OhTheWorld, CrazyCrates, XinxinBotShop, Fsell, GPS, JBank, PlotSquared, WorldGuard, Dantiao, RenameCard, WorldEditSUI, Essentials, TrMenu, MakeWishX-personal, PlayerInv, JulyGuild, Multiverse-Core, EWarp, QuickShop, AutoSpawnWorld, EssentialsProtect, DragonGPS, EssentialsSpawn, KeepInventory, Residence, AuthMe, MythicMobs, TradeMe, DreamRobot, LootChest, DungeonPlus, UltimateChairs, DragonArmourers, SkillAPI, FivePlanetSpawn, MythicMobsExtension, AkariLevel, AttributePlus, DreamSpawners, MythicAnimatorStands, AzureFlow, AP-Potion, MonsterManual, MythicArtifacts, AP-CowAttribute, MythicAttributePlaceholder, DreamShowcase, SimpleLib, DragonInventory, RuomoeCore, DreamCountdown, AttributeCompatibleAPI, DragonCore, D-AttSuit, FlameTabInfo, DragonAreaSound, DragonInteract, StarLibrary, SpawnProtect, DragonRide, RotateAnimation, DragonAnimation, DragonActivity, D-command, AttributePotion, DrFlyingSword, SenCore, LegendCore, LegendStrengthen, LegendCollapse, LegendPets, DreamAction, BukkitLibrary, StarCombatPro, RuomoeMap, StarTraders, StarKit, StarTaskView, StarTeam, StarSkillViewDrive, GDDPRevive
