### ISSUE TITLE
[issue] 兼容ia

### ISSUE THREAD

**Issue by CCjun6** [FlickerProjects/TrChat#452]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description
我把玩家的聊天颜色设置为了渐变色 但是当玩家输入:emj_doge:等这样的ia字符时 会不生效
![image](https://github.com/user-attachments/assets/89b1845e-ccbf-45cb-849e-24d5d911644f)

未生效:
![image](https://github.com/user-attachments/assets/921ca169-2b4b-41a3-b640-05dc4e73cc78)

尝试在:emj_doge:前面加&f也不会生效   &f:emj_doge:
![image](https://github.com/user-attachments/assets/f24f670b-3fb9-4547-9514-feb89398edda)

当不使用渐变色时 只是单一颜色就可以使用
![image](https://github.com/user-attachments/assets/916bd645-8fdc-4eda-b763-99b3ebbe5560)

有解决的方案吗

### configuration file

```YAML
msg:
      default-color: '<gradient:#98FB98:#BDFCC9:#A0F0EA:#BFFFE5>'
      hover: '&#DCDCDC消息发送时间: %server_time_h:mm:ss%'
```

### Server environment

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2324-e12a4de (MC: 1.21.1)

Trchat 2.2.0-beat6
