### ISSUE TITLE
[issue] Error on PacketInEvent

### ISSUE THREAD

**Issue by hseermc** [FlickerProjects/TrChat#455]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

不确定

### configuration file

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: 43.248.103.155
  port: 21826
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0
  Cooldown: '0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### logs

https://mclo.gs/Vz8FmH0

### Server environment

Server version:
leaves 1,21,1
Plugin list:
[22:50:01 INFO]: Server Plugins (98):
[22:50:01 INFO]: Paper Plugins:
[22:50:01 INFO]:  - HuskHomes
[22:50:01 INFO]: Bukkit Plugins:
[22:50:01 INFO]:  - AuthMe, BedrockPlayerSupport, BetterRTP, Bump, *ChineseName, Citizens, CMILib, CoreProtect, CrossplatForms, Cultivation
[22:50:01 INFO]:  CustomJoinAndLeaveMessages, DecentHolograms, DeluxeMenus, DynaTech, EClean, EcoPower, ElectricSpawners, ElementManipulation, Essentials, EssentialsSpawn
[22:50:01 INFO]:  EssentialsWarpGUI, ExoticGarden, ExtraGear, ExtraTools, FastMachines, FinalTECH-Changed, floodgate, Floodgate-Skript, FluffyMachines, FNAmplifications
[22:50:01 INFO]:  FoxyMachines, Gastronomicon, GeneticChickengineering, Geyser-Spigot, GlobalWarming, GroupManager, GSit, GuizhanCraft, GuizhanLibPlugin, HSEERTECH
[22:50:01 INFO]:  Images, InfiniteScoreboard, InfinityExpansion, InteractionVisualizer, InventoryRollbackPlus, ItemSwapperPlugin, LegendaryGuild, LiteAnnouncer, LiteSignIn, LiteXpansion
[22:50:01 INFO]:  mcMMO, MiniMOTD, MobCapturer, MomoTech, Multiverse-Core, Multiverse-NetherPortals, Networks, nightcore, PlaceholderAPI, PlayerTitle
[22:50:01 INFO]:  PlugManX, PrivateStorage, ProtocolLib, Quaptics, QuickShop-Hikari, RedstoneConnector, Residence, RykenSlimefunCustomizer, SFCalc, ShopGUIPlus
[22:50:01 INFO]:  ShopGUIPlus-SellGUI, SimpleMaterialGenerators, SimpleUtils, SkinsRestorer, Skript, skript-reflect, Slimefun, SlimefunWarfare, SlimeGlue, SlimeHUD
[22:50:01 INFO]:  SlimeTinker, SoulJars, Supreme, TAB, TimedRewards, TpaForm, TranscEndence, TrChat, UltimateAntiBot, UltimateAutoRestart
[22:50:01 INFO]:  UltimateGenerators, Uniporter, Vault, ViaBackwards, ViaVersion, XConomy, ZMusic
