### ISSUE TITLE
[问题] 1.12.2-Catserver-lib加载异常

### ISSUE THREAD

**Issue by Biliniko** [FlickerProjects/TrChat#462]
### 是否已尝试最新的版本

- [x] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [x] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

依赖库下载问题
`[12:34:09] [ForkJoinPool.commonPool-worker-23/INFO]: Downloading library com.mongodb:MongoDB:3.12.2 (transitive)
[12:34:41] [ForkJoinPool.commonPool-worker-23/WARN]: java.net.ConnectException: Connection timed out: connect`

Redis连接方法缺失：
`
java.lang.NoSuchMethodError: me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()Lcom/electronwill/nightconfig_3_6_7_3_6_7/core/Config;
`

### 配置文件

```YAML
settings.yml
`Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Use-Packets: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: 192.168.188.25
    port: 3306
    user: trchat
    password: *******
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: 192.168.188.25
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: false
  Book: true

Simple-Component:
  Hover: true
  Anvil: true
  Sign: true`
```

### 日志

[log.txt](https://github.com/user-attachments/files/18448922/log.txt)

### 服务器环境

服务器版本:

> This server is running CatServer version git-CatServer-1.12.2-090a6ffb (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)

插件列表:

> BeeSwitch, InfoQuery, PlaceholderAPI, Stp, JoinMessagePlus, UltimateAutoRestart, PlugMan, HomoParkourFix, homocmd, SkullAPI, MinePay, ConsoleSpamFix, TrChat, LoginTeleport, McBorder, NBTAPI, CoreProtect, MySqlAPI, LuckPerms, VoidGen, XinxinBotApi, GlobalGamerules, DreamCleaner, AntiOP, spark, NBTEditPanel, Cob, LiteBans, XinxinGroupCardLock, ModifyPlayer, ProtocolLib, Multiverse-Core, StartServerAutoCMD, Adyeshach, FastAsyncWorldEdit, Notbuild, AntiAttack, CatAntiCheatPlugin, MultiverseCoreBug, NBTLibrary, PlugManX, Vault, yuanluServerDo, eBackup, EastLandLog4jFixer, XinxinAutoReview, ServerVariables, OhTheWorld, Chemdah, XinxinCustomMessage, MysqlPlayerOnlinePapi, TAB-Bridge, GermPlugin, PlayerPoints, NoPlugins, PlayerTitle, Maintenance, WorldEdit, CtOnlineReward, YukiNoaAPI, PointLogger, HeadDatabase, XConomy, TrMenu, XinxinApi, XinxinBotShop, DeluxeHub, ajParkour, XinxinBotInfo, DecentHolograms, Essentials, EssentialsProtect, EssentialsSpawn, AuthMe, AuthmePapi, HomoTax, XinxinWhiteList, OfflinePlaceHolders, XinxinBotRegister
