### ISSUE TITLE
[问题] 1.21.1无法不在玩家名之前+@，触发at此玩家

### ISSUE THREAD

**Issue by Star6699** [FlickerProjects/TrChat#467]
### 是否已尝试最新的版本

- [x] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [x] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

此问题在1.20.1中可以使用，但是升级最新构建版本TrChat-2.2.2，我的世界1.21.1版本中无法使用，必需强制的在玩家名前面加上at才能触发at此玩家

### 配置文件

```YAML
Options:
  # 是否检查更新并提醒
  Check-Update: true
  # 强制使用跨服类型, 识别错误时可更改(AUTO, NONE, BUNGEE, VELOCITY)
  Proxy: AUTO
  # 记录普通聊天格式到plugins/TrChat/logs目录下的格式
  Log-Normal: '[{0}] {1}: {2}'
  # 记录私聊聊天格式到plugins/TrChat/logs目录下的格式
  Log-Private: '[{0}] {1} -> {2}: {3}'
  # 自动删除多少天前的聊天记录
  Log-Delete-Time: 0
  # 强制变量扩展
  Depend-Expansions: ['player', 'server']
  # 是否禁止玩家使用tab补全命令
  Prevent-Tab-Complete: false
  # 聊天发包最大长度限制
  Component-Max-Length: 32766
  # 是否允许Kether宽容解析
  Kether-Allow-Tolerance-Parser: true
  

# 默认频道
Channel:
  Default: '常规' # 改为Global即可全局跨服聊天

# 数据库
Database:
  # 数据库类型 (SQLite,SQL)
  Method: SQL
  SQL:
    # 数据库地址
    host: localhost
    # 数据库端口
    port: 3306
    # 数据库用户名
    user: root
    # 数据库密码
    password: root
    # 数据库名
    database: trchat
    # 数据库表名
    table: trchat_user_data

# Redis相关配置
Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

# 聊天功能
Chat:
  # 内容相似度防刷屏 (设为0禁用)
  Anti-Repeat: 0.75
  # 聊天间隔冷却
  Cooldown: '2s'
  # 最大聊天长度
  Length-Limit: 100

# 颜色转换
Color:
  # 聊天颜色
  Chat: true
  # 牌子颜色
  Sign: true
  # 铁砧颜色
  Anvil: true
  # 书本颜色
  Book: true

# 是否启用行内复合文本
Simple-Component:
  # 悬浮文字
  Hover: false
  # 铁砧
  Anvil: false
  # 告示牌
  Sign: false
```

### 服务器环境

服务器版本:
This server is running Leaves version 1.21.1-81-master@ec5a806 (2024-11-16T03:56:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-47-8be1ec2 (MC: 1.21.1)
插件列表:
[17:22:41 INFO]: Server Plugins (52):
[17:22:41 INFO]: Bukkit Plugins:
[17:22:41 INFO]:  - BetterRTP, BiliBiliToper, Chunky, CMI, CMILib, CoreProtect, Cyanidin-Backend, DecentHolograms, DeluxeMenus, DoubleDoors
[17:22:41 INFO]:  EasyBot, eBackup, EClean, GlobalMarketPlus, GSit, *HotkeyCommand, *Hub, ILoreEdit, ImageFrame, InsekiCodeKey
[17:22:41 INFO]:  LiteSignIn, LuckPerms, MapModCompanion, Matrix, NoMushroomInEnd, packetevents, PlaceholderAPI, Plan, PlayerInv, PlayerPoints
[17:22:41 INFO]:  PlayerStats, PlayerTitle, PlayTimeTracker, PlugManX, ProtocolLib, PyroFishingPro, PyroLib, QuickShop-Hikari, Residence, SetSpawn
[17:22:41 INFO]:  SuperHarvest, SweetMail, TAB-Bridge, TrChat, UltimateAutoRestart, UltimateShop, Vault, ViaBackwards, ViaRewind, ViaVersion
[17:22:41 INFO]:  voicechat, WorldEdit
