### ISSUE TITLE
1.21.1服务器下TrChat2.1.0的核心指令不可用

### ISSUE THREAD

**Issue by YY1433223bruh** [FlickerProjects/TrChat#469]
### 是否已尝试最新的版本

- [x] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [x] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

服务器为purpur-1.21.1-2299，安装并且正确加载TrChat指令后主要指令未注册并且全部无法使用

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: false
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0
  Cooldown: '0.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 服务器环境

服务器版本:Current Purpur Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)*
插件列表:
> plugins
[13:43:45 INFO]: Paper Plugins: (1):
[13:43:45 INFO]:  - BKCommonLib
[13:43:45 INFO]: Bukkit Plugins: (42):
[13:43:45 INFO]:  - AuthMe, AuxProtect, AxiomPaper, BetterShootReload, BlueMap, BoatCollisionDetector, Boom, Boom, Citizens, CMILib
[13:43:45 INFO]:  CoreProtect, CurveBuilding, *EasyWhitelist, FartherViewDistance, FastAsyncWorldEdit, floodgate, GSit, ImageFrame, ImageMaps, IronElevators
[13:43:45 INFO]:  LobbyGames, LuckPerms, Multiverse-Core, Multiverse-Portals, nightcore, OpenInv, PermanentTotem, PlaceholderAPI, PlugManX, ProtocolLib
[13:43:45 INFO]:  Residence, SkinsRestorer, SunLight, TAB, TabTPS, TrChat, Vault, ViaBackwards, ViaVersion, WorldBorder
[13:43:45 INFO]:  WorldEditSync, ZMusic
