### ISSUE TITLE
[issue] redis设置密码后 无法打字

### ISSUE THREAD

**Issue by CCjun6** [FlickerProjects/TrChat#475]
### Whether the latest version has been tried

- [x] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [x] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

![Image](https://github.com/user-attachments/assets/5d117288-9cca-49b3-a486-f511d2446554)

![Image](https://github.com/user-attachments/assets/20fe0996-beed-460b-925a-a49c151da6c5)

显示连接成功了 但是进入游戏后无法打字 如果redis没有设置密码 就可以正常使用

### configuration file

```YAML
Options:
  # 是否检查插件更新
  Check-Update: true
  # 代理设置：AUTO 表示自动选择代理类型，可能会根据环境自动配置
  Proxy: AUTO
  # 日志输出格式 - 普通日志
  # {0} 代表时间戳, {1} 代表发消息的玩家, {2} 代表消息内容
  Log-Normal: '[{0}] {1}: {2}'
  # 日志输出格式 - 私密日志
  # {0} 代表时间戳, {1} 代表发消息的玩家, {2} 代表接收消息的玩家, {3} 代表消息内容
  Log-Private: '[{0}] {1} -> {2}: {3}'
  # 删除日志的时间（单位：秒），0 表示不删除日志
  Log-Delete-Time: 0
  # 插件所依赖的扩展模块
  # 例如：'player' 代表玩家相关的扩展, 'server' 代表服务器相关的扩展
  Depend-Expansions: ['player', 'server']
  # 是否防止自动补全命令（通常是指聊天时的自动补全功能）
  Prevent-Tab-Complete: false
  # 组件最大长度（例如聊天消息的最大长度限制）
  Component-Max-Length: 100000
  # 是否总是取消聊天事件（即使在某些情况下聊天事件可能会被触发）
  Always-Cancel-Chat-Event: false
  # 是否启用防作弊客户端的安全聊天功能（用于防止作弊客户端干扰聊天）
  Cheat-Client-Secure-Chat: true
  # 是否使用数据包来处理聊天（可能提高性能或兼容性）
  Use-Packets: true
  # 禁用的命令列表，留空表示没有禁用的命令
  Disabled-Commands: []

Channel:
  # 默认频道设置，'Normal' 可能是指普通聊天频道
  Default: 'Global'

Database:
  Method: MySQL
  SQL:
    host: localhost
    port: 3306
    user: root
    password: 134679a
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6379
  user: ''
  password: '123456'
  connect: 32
  timeout: 1000

Chat:
  # 反复发送相似消息的检测阈值
  # 如果用户在此值设置的百分比内重复发送相似消息，将触发反作弊机制
  Anti-Repeat: 0.85
  # 聊天消息的冷却时间
  # 用户发送消息后，需要等待此时间才能再次发送消息，格式为 '秒'
  Cooldown: '2.0s'
  # 聊天消息的最大长度限制
  # 设定单条消息的最大字符长度
  Length-Limit: 100


Color:
  # 是否启用聊天中的颜色显示
  Chat: true
  # 是否启用告示牌中的颜色显示
  Sign: true
  # 是否启用铁砧中的颜色显示
  Anvil: true
  # 是否启用书籍中的颜色显示
  Book: true

Simple-Component:
  # 是否启用悬停效果（如鼠标悬停时显示的提示） 
  Hover: false
  # 是否启用铁砧界面的简单组件（如铁砧中使用的简单文本或组件）
  Anvil: false
  # 是否启用告示牌界面的简单组件（如告示牌中使用的简单文本或组件）
  Sign: false
```

### Server environment

Server version:
...1.21.4
Plugin list:
...
