### ISSUE TITLE
加入更改mention提示音的选项

### ISSUE THREAD

**Issue by Dreeam-qwq** [FlickerProjects/TrChat#55]
如题
加个选项可以更改@提示的声音awa

**Comment by ItsFlicker** [comment]
在语言文件(zh_CN.yml)中的
```yaml
Mentions-Notify:
  - type: actionbar
    text: '&d&l&k|&r &3&l玩家 &a&l{0} &3&l在聊天中At了你 &d&l&k|'
  - type: sound
    sound: 'BLOCK_ANVIL_LAND'
    volume: 1
    pitch: 2
```
处修改sound就可以更改声音了
